OctopusDeploy/OctopusTentacle

docker-compose.build.yml
As we're not using it, and having trouble with docker on - it's not stable
We started adding support for docker images for windows 20H2, but 20H2 is causing more pain than it's worth. It never made it out the door.
Dropping it to reduce complexity.
A simple sanity check of the idea will suffice.
=> Drop the windows 20h2 docker image

linux-packages/packaging-scripts/create-linux-packages.sh, source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Tests/Communications/AutofacServiceFactoryFixture.cs, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle/Communications/AutofacServiceFactory.cs, source/Octopus.Tentacle/Communications/HalibutInitializer.cs, source/Octopus.Tentacle/Communications/IAutofacServiceSource.cs, source/Octopus.Tentacle/Communications/InvalidServiceTypeException.cs, source/Octopus.Tentacle/Communications/KnownServiceSource.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Communications/UnknownServiceNameException.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Services/ServicesModule.cs
Halibut has been updated to make the protocol more secure.
In the process, the AutofacServiceFactory has been moved from shared to here.
=> Update Halibut and move AutofacServiceFactory to Tentacle

docker/linux/scripts/configure-tentacle.sh
Even if the "i am configured" semaphore exists
If the `.configuredSemaphore` file exists, the Tentacle container wont attempt to reconfigure.
In https://github.com/OctopusDeploy/OctopusTentacle/pull/290, we changed it from completely aborting to "ignore reconfiguration and continue". 
However, in the wild (ie, on my nas), the new container, I found that sometimes it still would be unable to launch, as the binary had not been linked into the expected location.
This PR changes the order, so that if the symbolic link does not exist, it creates that before checking if the semaphore exists.
Here are the steps I used to test this pull request:
```
docker run `
--interactive `
--detach `
--name OctopusTentacle10996 `
--publish 10996:10996 `
--env "ListeningPort=10996" `
--env …
```
=> Ensure Tentacle binary is linked on new container

source/Octopus.Tentacle.Tests/Commands/RegisterMachineCommandFixture.cs, source/Octopus.Tentacle.Tests/Commands/RegisterWorkerCommandFixture.cs, source/Octopus.Tentacle/Commands/OptionSets/IOctopusClientInitializer.cs, source/Octopus.Tentacle/Commands/OptionSets/OctopusClientInitializer.cs, source/Octopus.Tentacle/Commands/RegisterMachineCommandBase.cs, source/Octopus.Tentacle/Communications/OctopusServerChecker.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Polling tentacles currently ignore the `UseDefaultProxy` setting when registering, and will attempt to use the default proxy on Windows if no specific proxy is configured. 
Fixes https://github.com/OctopusDeploy/Issues/issues/7065
Added `allowDefaultProxy` parameter to `OctopusClientInitializer`, and passed it to the client creater. This allows the configuration value of `UseDefaultProxy` to be used for polling tentacles on registration.
Here are the steps I used to test this pull request:
- Setup a broken default proxy
- Attempted to register a pre-fix tentacle with a remote server
- Failed 😢 
- Attempted to register a post-fix tentacle with a remote server
- Success 🥳🍾:tada:   
A double check that this won't effect existing …
=> Fix UseDefaultProxy setting for tentacle registration

source/Octopus.Tentacle.Tests/Commands/StubTentacleConfiguration.cs, source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Configuration/ITentacleConfiguration.cs, source/Octopus.Tentacle/Configuration/TentacleConfiguration.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Package retention requires a new journal file to be stored on the Tentacle to keep track of package usages. This PR adds a new environment variable similar to the existing `JournalPath` used for deployments which we can use in Calamari to retrieve the correct file.
=> Add PackageRetentionJournal environment variable

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Also updated `HalibutRuntime`, as there was an error saying its obsolete (change from v4.4.8?)
=> Upgrade to Halibut 4.4.9

source/Octopus.Tentacle/Configuration/TentacleConfiguration.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
This is to deal with changes in the later .NET SDKs that cause Visual Studio and Rider, and sometimes the builds, to hit errors.
👀 the code, there are only a few lines.
=> Adjustments to more Nullable Reference Type things for Configuration

source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs
This works in conjunctions with the changes to Octopus Shared that allows passing a script isolation mutex name with a command: https://github.com/OctopusDeploy/OctopusShared/pull/165
This PR sets the isolation mutex name on the workspace to match the name sent with the command.
=> Pass isolation mutex name to workspace

docker/windows/Scripts/configure-tentacle.ps1
Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/208
```
[2021-12-09T01:49:52] Registering with server ...
[2021-12-09T01:49:52] Executing command 'C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe register-worker --console --instance Tentacle --server http://dr-octopus.corp.adslot.com --force --comms-style TentacleActive --server-comms-port 10943 --apiKey **apiKeyWouldAppearHere** --name octopus-worker-win-dr --workerpool Default Worker Pool --space "Default"'
```
With API key:
With username/password:
With API key:
With username/password:
=> Mask sensitive values in Windows Tentacle container creation logs

docker/linux/Dockerfile, docker/linux/scripts/configure-tentacle.sh, docker/readme.md, docker/windows/Scripts/configure-tentacle.ps1
Tentacle allows you to specify Tenants/TenantTags via the CLI. Currently these options don't exist when running a new Tentacle Docker container.
Fixes https://github.com/OctopusDeploy/Issues/issues/7251
This PR also adds some documentation for the `Space` and `MachinePolicy` environment variables - currently both of these can be configured for the Linux image, but only `Space` existed for the Windows image. Neither of these were included in the readme, so I've added some documentation for these as well.
Tentacles could not be created with Tenant options
Default Tentacle with no extra options:
Tentacle with Tenant (`--env TargetTenant="T1"`):
Tentacle with Tenant Tag (`--env TargetTenantTag="TS1/TT1"`):
Tentacle with Tenanted Deployment Mode (`--env …
=> Add Tenant/TenantTag/TenantedDeploymentParticipation options to Tentacle docker image, add documentation for Space/MachinePolicy options

docker/linux/scripts/configure-tentacle.sh
Our documentation states that the Tentacle running in a Docker container will be running on port 10933. This works for the Windows Tentacle image as the internal port is always configured with a default value. However, the Linux Tentacle image configures the internal port with the environment variable ListeningPort. This is the same environment variable that is used to register the Tentacle with Octopus Server (this is the same in both Linux and Windows). There are two problems with this:
1. The Tentacle in Linux Docker does not always run on the internal port 10933
2. Docker images allow the user to map an internal port to a different host port (eg. for a web server like nginx the internal port is 80, but this can be mapped to a known unused port like 12321 on the host with -p 12321:80). …
=> Set default internal listening port for Linux docker image

build/Build.Tests.cs
Centos 8 is EOL. See https://www.centos.org/centos-linux-eol/
I don't think we need an alternative - Centos Stream is the replacement but does not have an image on Docker and does not appear in .NET supported operating systems.
Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/279
=> Remove Centos:latest package test

source/Octopus.Tentacle/Octopus.Tentacle.csproj
Improves security related to certificates by making use of the changes made in https://github.com/OctopusDeploy/OctopusShared/pull/169 .
Fixes: https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/228
=> Make use of ephemeral keys

build/Build.cs
When installing Octopus Tentacle version 6.1.1056 or newer, the Octopus Server UI correctly displays the Tentacle Version, however Windows shows Version 1.0.0.0 is installed.
Fixes https://github.com/OctopusDeploy/Issues/issues/7298
It looks like a minor detail was missed in the [Cake -> Nuke](https://github.com/OctopusDeploy/OctopusTentacle/pull/308) conversion. The original wxs file reference was being returned, so the version was being set to the default even though we actually save the file correctly.
=> Get updated .wxs file reference in build

source/Octopus.Tentacle/Octopus.Tentacle.csproj
Bumps the `Octopus.Shared` version to pull in the fix in https://github.com/OctopusDeploy/OctopusShared/pull/173
=> bump Octopus.Shared version

build/Build.Tests.cs
Ubuntu image for latest and rolling is now 22.04 
dotnet core isn't supported yet. https://github.com/dotnet/core/issues/7038
Unable to install libssl1.1 as it's not in 22.04
just going to not test against it for now. We don't officially support latest 
Here are the steps I used to test this pull request:
- teamcity build should pass
=> No support for dotnet core in 22.04 

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
The is, if octopus server closes the stream, tentacle will consume 100% CPU trying to read the rest of the stream.
The fix is actually in: https://github.com/OctopusDeploy/Halibut/pull/142
Fixes: https://github.com/OctopusDeploy/OctopusTentacle/issues/360
Does this make sense?
=> Fix the stream closed halibut bug.

build/Build.Tests.cs
The `fedora:latest` image was updated to Fedora 36 on [May 13](https://build.octopushq.com/buildConfiguration/OctopusDeploy_OctopusTentacle_TestLinuxPackages/4305431?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false). I'm pretty certain Fedora 36 doesn't support dotnet core yet but there's only an issue for Fedora 37 for some reason - https://github.com/dotnet/core/issues/7467. It has the same issue as https://github.com/OctopusDeploy/OctopusTentacle/pull/364 where it's unable to install libssl1.1.
🔴 https://build.octopushq.com/buildConfiguration/OctopusDeploy_OctopusTentacle_TestLinuxPackages?mode=builds#all-projects
Hopefully 🟢 
Here are the steps I used to test this pull request:
- TeamCity build passes …
=> Use Fedora 35 image in test

.nuke/build.schema.json, build/Build.Pack.cs, build/Build.Tests.cs, build/Build.cs, build/Configuration.cs, build/Git.cs, build/Logging.cs, build/ModifiableFileWithRestoreContentsOnDispose.cs, build/Signing.cs, build/_build.csproj, global.json, linux-packages/packaging-scripts/package.sh
Changes:
- Moving methods around to flow more sequentially as you go down the file
- Reduce the number of duplicated dependencies
- Remove obsolete methods and replace with suggested ones (Nuke.Logger -> Serilog.Log, Nuke.ControlFlow -> Assert)
- Update versions of tools
- Update SDK version
Changes on TeamCity:
- Cloned old Tentacle project https://build.octopushq.com/admin/editProject.html?projectId=OctopusDeploy_OctopusTentacleSensibleDefaults
- Cleaned up agent requirements
- Cleaned up build steps (some running through bash were using `build.cmd` instead of `build.sh`)
=> Update Nuke build

build/Build.cs
Tentacle is using the OctoVersion TeamCity plugin. This overwrites the `-nightly` suffix resulting in nightly builds getting pushed to release. We should rely on `OctoVersion.Tool` generating the version for us instead.
=> Add CalculateVersion target

.nuke/build.schema.json, build/Build.cs, build/Signing.cs, build/_build.csproj
AZ signing tool was breaking the nightly builds with a requirement for older donet sdks which are not in our build servers.
https://octopusdeploy.slack.com/archives/C01HH8T16G3/p1656285647847579 (internal link)
Bumping version for the tool and adding in the tenant parameters 
=> update azure signing tool and fix new breaking change

build/_build.csproj
Net5 is EOL, build agents will no longer include it
Nuke is still on net5, bumped it to net6
=> bump nuke to net6

source/Octopus.Tentacle.Upgrader/Program.cs
As part of the Tentacle upgrade work, this reduces the need to upload both msi files when we already know the architecture of a machine.
Relates to https://github.com/OctopusDeploy/Issues/issues/7082
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/388 (this is mainly so we can get a "meaningful change" for this Tentacle release so that the release is publicly available)
=> Allow only one msi when upgrading to slim down Tentacle upgrade

build/Build.Pack.cs
This will publish the contract NuGet package as it now adheres to the package push convention.
=> Pack contracts to nuget directory

docker/linux/Dockerfile, docker/linux/install-scripts/install-docker.sh
Fixes #381 .
1. Push the changes; wait until a prerelease build is ready.
2. `docker run -it --rm ...` that generated image.
3. Confirm that Tentacle can run Docker-in-Docker commands on relevant virtual machines.
To do the last:
```bash
docker run -it --rm --privileged docker.packages.octopushq.com/octopusdeploy/tentacle:<version_from_build> bash
```
In the resulting Docker container:
```
/scripts/dockerd-entrypoint.sh &
docker ps
docker run -it --rm alpine pwd
```
* We previously used a `curl`ed script to install Docker; however, the installation procedure using apt is now much more usable.
* Ultimately, all this really does is version-bumps Docker using a nicer installation mechanism.
* It would be good to better understand …
=> Use apt to install the latest Docker daemon and upgrade docker-ce

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Manager.Tentacle/packages.config, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle.Upgrader/Octopus.Tentacle.Upgrader.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
InteropServices is built into net4.8+
[sc-27778]
=> Remove InteropServices from dependencies

source/Octopus.Tentacle/Util/OctopusPhysicalFileSystem.cs
Our current free space calculation is very windows focused, and makes assumptions that are nearly always true in the windows world, but much less common in the linux world.
Specifically, it  checks for free disk space on the drive root, rather than the specified directory.
So, if we're on windows and we're checking for diskspace on the drive that contains `c:\octopus\tentacle\work`, we're checking how much space `c:\` has. This is nearly always safe, as it's comparitively rare [citation needed] for symlinks to be used on windows.
On linux, when we check for diskspace on the drive that contains `/data/octopus/Tentacle/Work/20221216053244-31899-1`, we end up checking `/`, which may be a completely different drive.
On one of my servers, `/data` is a mount point 
```
df
Filesystem …
```
=> Dont only check free space on the root of the drive

build/Build.Tests.cs
Currently we build the Tentacle solution and publish binaries as artifacts. Our tests depend on the artifacts, but then rebuild each time a test runs. We are not testing the binaries that we ship. This PR removes the build phase from our tests.
=> Prevent tests from rebuilding binaries

source/Octopus.Tentacle/Octopus.Tentacle.csproj
We're seeing the `CultureNotFoundException` in some cases after upgrading to net6.
> Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
> en is an invalid culture identifier.
> System.Globalization.CultureNotFoundException
>    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
>    at System.Globalization.CultureInfo..ctor(String name)
>    at System.Globalization.CultureInfo.CreateSpecificCulture(String name)
>    at Microsoft.Win32.TaskScheduler.Trigger..cctor()
This is probably due to https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode
Allow the existing behaviour to continue without …
=> fix invariant

source/Octopus.Tentacle/Octopus.Tentacle.csproj
This repository looks to have just been left around form the Octopus.Shared migration, and even then its [not clear why](https://github.com/OctopusDeploy/OctopusShared/commit/a81c5f497e8471f2c10dd6f6e502b9287362bc1c#diff-2bdf99562d36573c1b83f6dde18db0b16fa58f16f4e1b3db754177eec45084e5R75) it would be needed.
A question has been raised by a customer if it is required, so removing from the project to remove any doubt.
=> Remove mono.posix.netstandard

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle/Commands/OptionSets/ApiEndpointOptions.cs, source/Octopus.Tentacle/Commands/OptionSets/OctopusClientInitializer.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
[sc-41739]
When registering a polling tentacle with an Octopus instance using an untrusted certificate, such as a self signed cert, the HTTP connection to complete the registration will fail with certificate errors.
There is also no workaround to register a polling tentacle. 
Added `--ignoreSslErrors` to the worker registration commands to allow users to opt in to avoiding the ssl errors
This argument is only added for .net 6 builds.
MacOS:
```
❯ ./Tentacle register-worker --instance Tentacle --server https://benpearcedb83 --apikey API-BMSPN8T7SIA80WVE1OPACOXAIHBL8XM --name ssl-test --workerPool "Default Worker Pool" --comms-
style TentacleActive --server-comms-port 10943
Checking connectivity on the server communications port 10943...
Connected successfully
Registering the tentacle with …
```
=> add `ignoreSslErrors` to machine registration commands

docker/readme.md
[sc-36158]
This PR documents the docker environment variable `ServerCommsAddress` in the docker README as per the updates made on [Docker Hub](https://hub.docker.com/r/octopusdeploy/tentacle). This env var was introduced in #440. 
=> Add ServerCommsAddress env var to the docker README

docker/Tests/OpenPorts.Tests.ps1, docker/common.ps1, docker/readme.md, docker/run-tests.ps1
The copy in this file, and the copy viewable at https://hub.docker.com/r/octopusdeploy/tentacle, are synced manually. This commit just updates the repo copy to match the updated online copy.
Fixes internal issue [sc-44418]
=> Update Docker readme to match online copy

source/Octopus.Tentacle.Contracts/Legacy/AssemblyMappingSerializationBinderDecorator.cs, source/Octopus.Tentacle.Contracts/Legacy/MessageSerializerBuilderExtensionMethods.cs, source/Octopus.Tentacle.Contracts/Legacy/NamespaceMappingSerializationBinderDecorator.cs, source/Octopus.Tentacle.Contracts/Legacy/ReMappedLegacyTypes.cs, source/Octopus.Tentacle.Tests/Contracts/Legacy/AssemblyMappingSerializationBinderDecoratorFixture.cs, source/Octopus.Tentacle.Tests/Contracts/Legacy/CanSerializeAndDeserializeJsonWithLegacyNameSpace.cs, source/Octopus.Tentacle.Tests/Util/DataStreamExtensionMethods.cs, source/Octopus.Tentacle.Tests/Util/SerializationExtensionMethods.cs
Prevents new tentacle contracts from being mapped to the old `Octopus.Shared` assembly and `Octopus.Shared.Contracts` namespace within halibut communications.
New classes will be serialized without the `$type` section of the json from being modified.
[SC-46982]
Any new classes added will be serialized and deserialized normally and wont require any hacking of namespaces or assemblies.
No test can be written for new types since, we don't have any new types to test with.
=> Only map existing contracts

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Contracts/Capabilities/BackwardsCompatibleCapabilitiesDecorator.cs, source/Octopus.Tentacle.Contracts/Capabilities/ICapabilitiesService.cs, source/Octopus.Tentacle.Contracts/Capabilities/ICapabilitiesServiceExtensionMethods.cs, source/Octopus.Tentacle.Contracts/CapabilitiesResponse.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests/Capabilities/BackwardsCompatibleCapabilitiesDecoratorFixture.cs, source/Octopus.Tentacle.Tests/Capabilities/CapabilitiesServiceFixture.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Services/Capabilities/CapabilitiesService.cs
Adds a capabilities service to make it easier to discover what capabilities the remote Tentacle supports. This will make it easier for clients to work out what it can do with the Tentacle.
Adds a backwards compatible capabilities service. The service returns a list of the capabilities of tentacle. Currently it returns an empty list which mean tentacle supports the current set of tentacle features.
The capabilities service is backwards compatible with older Tentacles which do not have a capabilities service. This is done by wrapping a Halibut created `ICapabilitiesDecorator` with a `BackwardsCompatibleCapabilitiesDecorator`. That can be done with the extension method `WithBackwardsCompatability`. See the test for an example.
=> Adds a capabilities service to Tentacle.

build/Build.Tests.cs
Automated package installation tests against the Debian distribution `oldoldstable` have started failing from 24/4/2023 ([example failing build](https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacleNet48_SensibleDefaultsTestLinuxPackages/7563276?buildTab=tests&expandedTest=build%3A%28id%3A7563276%29%2Cid%3A1715) - internal link). This distribution was linked to Debian 9 (Stretch) which is EOL as of June 2022. 
It appears that the link was removed from http://deb.debian.org/debian causing the test failures, although we haven't been able to find any announcements about this. We believe this is likely because a new major version of Debian will be released in the new few months.
These failures are blocking our ability to ship any changes for Tentacle.
See …
=> Remove Debian `oldoldstable` from linux test packages list

source/Octopus.Tentacle.Tests.Integration/Startup/LinuxConfigureServiceHelperFixture.cs
Two integration tests have been failing for Linux since the agent on which the tests run got updated from Ubuntu 16 to 18.
- CanInstallServiceAsRoot
- CanInstallServiceAsUser
These have been failing with an error message "System.IndexOutOfRangeException : Index was outside the bounds of the array.". The tests attempt to install the tentacle service and then check a bunch of properties using `systemctl`. Changing to Ubuntu 18 looks like its added in a couple of properties that have an empty string as their value:
The test hasn't handled these well and caused the failure.
This PR fixes the test so that it allows values with empty strings to return in the property set that is gathered from the installed service. We only check a few specific properties, so allowing others that we don't care …
=> Fixes failing service installation tests on Linux

source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/PollingTentacleTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ITentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/LinuxTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/NugetTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/OctopusPackageDownloader.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleExeFinder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetcherFactory.cs
We are going to make changes to tentacle and need clients to still be able to talk to older tentacle.
This adds the ability to wrote those tests, which will be used in a future PR which adds a working capability service.
[SC-46171]
An existing version of tentacle can now be downloaded unpacked and run in a test.
The tentacle is cached locally for speedy development locally.
=> Adds support for testing against existing versions of tentacles

source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs
This enables as to test what happens when tentacle is terminated while running a script and is later started up again.
=> Adds the ability to start and stop tentacles in Integration Tests

source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/Util/PortForwarderBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/SerilogLoggerBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/PortForwarder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/SocketPump.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/TCPListenerWhichKillsNewConnections.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/TcpPump.cs
This will allow us to test retries when the network connection has an issue.
The portforwarder itself comes from Halibut see [here](https://github.com/OctopusDeploy/Halibut/pull/235). Eventually it will be rolled into its own solution and nuget package but until then this lets us write the tests we need now.
=> Adds the Port Forwarder test util to tentacle.

source/Octopus.Tentacle.Contracts/Legacy/HalibutRuntimeExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ListeningTentacleTests.cs, source/Octopus.Tentacle.Tests.Integration/PollingTentacleTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleClientBuilderExtensionMethods.cs
This PR adds the ability to test a listening tentacle with the TentacleClient, as part of [[sc-46171]](https://app.shortcut.com/octopusdeploy/story/46171/tentacle-client-tests)
* Add `ListeningTentacleBuilder`
* Add basic comms tests to ensure that TentacleClient can connect/communicate with a listening tentacle.
* Refactor builder classes to remove code duplication
=> Add support for testing listening tentacles with TentacleClient

source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
Also give test tentacle instances a better name.
[SC-46171]
Previously after a tentacle integration test run, a tentacle instance would be left on the host machine. With this change that tentacle instance will be deleted if the test completes (even in failure).
=> Delete Test Tentacle instances.

source/Octopus.Tentacle.Tests.Integration/Support/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetcherFactory.cs
Stop downloading tentacle so many times:
Tests download the same tentacle over and over.
```
cat ~/Downloads/Octopus_Tentacle_Integration_Test_Linux_6.3.781-pull-498.log | grep Downloading | grep " to " | wc
56     336   12440
```
// Now they do not.
```
cat ~/Downloads/Octopus_Tentacle_Integration_Test_Linux_6.3.784-pull-499.log | grep Downloading | grep " to " | wc
6      36    1326
```
=> Add caching

source/Octopus.Tentacle.Upgrader/ServiceBouncer.cs, source/Octopus.Tentacle/Startup/WindowsServiceConfigurator.cs
Background
Server was taking sc.exe files from locations other than system32 path, where that file should always be. This could lead to server picking up maliciously downloaded files.
Server fix: https://github.com/OctopusDeploy/OctopusDeploy/pull/18247
Fixes [[sc-39057](https://app.shortcut.com/octopusdeploy/story/39057)]
Results
Use full path of sc.exe as it should always be in the same location
=> Use full path for sc.exe file 

source/Octopus.Tentacle.Client/ITentacleClient.cs, source/Octopus.Tentacle.Client/Scripts/ScriptExecutionResult.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/TentacleClientExtensionMethods.cs
Script Execution used to return a `ScriptStatusResponseV2`. These meant that running a script with `ExecuteScript()` would return a result that contains `logs` which was always empty and `nextSequence` which is useless.
The change here is to return a new type which doesn't have those misleading property in the object. Doing so should prevent clients from accidentally using the empty logs property.
=> Script execution now returns a dedicated type.

source/Octopus.Tentacle.Client/Octopus.Tentacle.Client.csproj, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
This PR drops support for netstandard for the Contracts and Client projects.
These are used internally.
This work was being done under RPC Retries but is needed now for a small Halibut fix.
=> Drop support for netstandard now that Halibut is net48 and net6 only

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/Support/AllCombinations.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationObservingPendingRequestQueueFactory.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationTokenObservingPendingRequestQueueDecorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/PendingRequestQueueWorkarounds.cs, source/Octopus.Tentacle.Tests.Integration/Util/SerilogLoggerBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/ResponseMessageTcpKillerWorkarounds.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/PortForwarder.cs, source/Octopus.Tentacle/Util/SemaphoreSlimExtensions.cs
`ClientScriptExecutionCanBeCancelled` was flaky , the following changes address that:
* Introduced a new mode to the Port Forwarder in which new and existing connections will be terminated immediately.
* Updated  all tests which previously stopped and started the Port Forwarder to use that. Preventing Port is already in use errors from occurring. 
* `AddCertificateToTentacle` is now done after configuring the Application dir, which reduces race conditions in running tentacle externally. The issue here is tentacles lists all instances of tentacle on a machine including those not completely setup.
* Exceptions thrown from deleting an instance after a test has run is now ignored, avoiding the race condition above from affecting the tests.
* Added a …
=> Fixes ClientScriptExecutionCanBeCancelled from being flaky

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Microsoft published a [security update](https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b) on 13th June 2023 regarding how .NET applications import x509 certificates.
This PR updates Octopus Tentacle to the [updated version of Halibut](https://github.com/OctopusDeploy/Halibut/pull/243), which supports these changes.
The changes are as per the [recommended approach](https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b#:~:text=//%20RECOMMENDED%20WORKAROUND%20%2D%20different%20ctor%20overload%20suppresses%20additional%20security%20checks%20X509Certificate2%20certB%20%3D%20new%20X509Certificate2(blobToImport …
=> Update contracts to use the latest version of Halibut that fixes x509 issue

build/Build.cs, source/Octopus.Tentacle.Client/Octopus.Tentacle.Client.csproj, source/Octopus.Tentacle.CommonTestUtils/Octopus.Tentacle.CommonTestUtils.csproj, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Tentacle.sln
Running E2E tests on an M1 Mac were failing, as it was trying to run the `osx-x64` version.
This adds a new publish target for `osx-arm64`
=> Add arm64 OSX build for M1 macs

docker/linux/install-scripts/install-docker.sh
Some newer linux operating systems are moving away from iptables to iptables-nft. This can cause issues with running docker in docker when running tentacles inside a container.
> [...iptables-nft can supplant iptables-legacy...](https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables#summary)
Users are now able to run execution containers inside a tentacle, running on a container in some linux hosts on different kernel modules for iptables.
```
INFO[2023-06-18T21:13:35.633790633Z] unable to detect if iptables supports xlock: 'iptables --wait -L -n': `modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-348.el8.x86_64
iptables v1.8.7 (legacy): can't initialize iptables table `filter': Table does not exist (do you …
```
=> Symlink iptables-nft instead of iptables-legacy for iptables based on availability

source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs, source/Octopus.Tentacle/Util/SilentProcessRunner.cs
There's been a recent increase of intermittently failing integration tests for cancellation of running scripts on Linux. 
This has been tracked down to the way that we currently do process cleanup in Linux:
- Run a bash script `kill -TERM {pid}` and check this succeeded
- Check if the process has exited (`Process.HasExited`) and close the process to ensure that it releases any underlying resources (`Process.Close`). 
- Wait for the process to exit: `Process.WaitForExit()`.
It appears that sometimes `Process.HasExited` returns false and we don't close the underlying process resource, and this causes `WaitForExit` to block until the process finishes. Whether the process never really receives the call to exit properly, or there is some strange behaviour with child processes and output …
=> Use Process.Kill recursive API when cancelling scripts in .NET 6

source/Octopus.Tentacle.Contracts/Observability/TimedOperation.cs
[sc-46303]
While writing unit tests in Octopus Server, we needed to craft the `TimedOperation` appropriately.
Fixes https://github.com/OctopusDeploy/Issues/issues/8229
There was no way of changing the values of a `TimedOperation`
The constructor is now public, allowing us to make the appropriate scenarios in Octopus Server
=> Making TimedOperation constructor public

source/Octopus.Tentacle.Client/Execution/RpcCallExecutor.cs, source/Octopus.Tentacle.Client/Observability/RpcCallMetricsBuilder.cs, source/Octopus.Tentacle.Client/Scripts/ScriptExecutionOrchestrator.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Contracts/Observability/RpcCall.cs, source/Octopus.Tentacle.Contracts/Observability/RpcCallMetrics.cs, source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests/Client/RpcCallExecutorFixture.cs
[sc-52746]
We need to know if our new feature is being used. To populate the respective metrics in Octopus Server, we will achieve this by knowing which service was called.
Related to https://github.com/OctopusDeploy/Issues/issues/8229
Only the method name was recorded in the metrics.
The service name is added as well.
We went with the name of the interface instead of the object, as the object tends to be a decorator and other unhelpful classes.
=> Adding which service was called to RPC metrics

source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj
The nightly build for Tentacle has been intermittently failing due to the test runner failing to parse the report file.
There's no exact area that can pinpoint the issue, however, one of the potential causes could be the outdated `TeamCity.VSTest.TestAdapter` plugin used in Tentacle.
Updating the version to the (latest available) `1.0.36`
- There're a number of [fixes](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/releases) since the `1.0.15` release
=> Use the updated (latest available) TeamCity.VSTest.TestAdapter.

source/Octopus.Tentacle.Client/Scripts/ScriptExecutionOrchestrator.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests/Client/RpcCallExecutorFixture.cs
[sc-53091]
The tentacle client observability work recorded the service names as `IClient....`
But to ensure the metrics continue from what was originally called, we need to remove the Client part.
Related to https://github.com/OctopusDeploy/Issues/issues/8229
Service names had the `Client` version of the service observed
We now have the non-Client version of the service observed
A touch of code tidying was done. But not much.
=> Renaming services to be inline with existing logging

source/Octopus.Tentacle.Client/ITentacleServiceDecorator.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs
Makes the service decorators internal, to avoid clients depending on it.
[SC-51186]
=> The service decorator interface is now internal

source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs
Stop the TentacleClient constructor configuring the error response caching for Halibut, as this results in the HalibutRuntime being configured every time the TentacleClient is created rather than once.
TentacleClient was being retained in Memory due to the reference created registering the ErrorResponseMessageCachingAction
The delegate handler chain for OverideErrorResponseMessageCachingAction had a new action added to the chain for every TentacleClient created
Server / other clients will have to perform an additional call to configure Halibut for Tentacle Client usage, which is not ideal but we need to ensure this is only done once.
`TentacleClient.CacheServiceWasNotFoundResponseMessages(halibutRuntime);`
=> Change how Error Response Caching is configured for the Halibut Runtime when using TentacleClient

source/Octopus.Tentacle.Client/Retries/RpcCallRetryHandler.cs, source/Octopus.Tentacle.Client/Retries/TaskExtensionMethods.cs
As part of TentacleClient script execution, cancelling a script execution can result in the task performing the RPC call to be abandoned and not awaited.
If an error is thrown by this abandoned task, it will result in the Finalizer handling and rethrowing the exception as it has not been observed.
If the task is being abandoned and Fails, we wrap it in a ContinueWith to ensure the exception is observer
No automated Testing has been added for this issue, but it has been manually verified that the unobserved error no longer exists.
```
From 89f26012a742adb2888b8937f829c07bf4ee2a8a Mon Sep 17 00:00:00 2001
From: Nathan Willoughby <nathan.willoughby@octopus.com>
Date: Sat, 8 Jul 2023 21:25:15 +1000
Subject: [PATCH] Manually Test Unobserved Exception
---
.../SetUpFixtures.cs …
```
=> Observe errors from task that are abandoned to stop UnobservedExceptions being handled by the Finalizer

source/Octopus.Tentacle.Client/Capabilities/CapabilitiesResponseV2ExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests/Capabilities/CapabilitiesServiceV2Fixture.cs, source/Octopus.Tentacle/Services/Capabilities/CapabilitiesServiceV2.cs
As part of rolling out RPC Retries, we will remove the Alpha label from ScriptServiceV2 before we rollout to Production.
This PR will not be merged until we reach [Stage II of rollout](https://docs.google.com/document/d/15drkongEmMkUP1viPKk-LyxFC2AxfnD5e5MgQK0VCs8/edit#heading=h.vhq8icw36cx7)
Related Server change https://github.com/OctopusDeploy/OctopusDeploy/pull/19057
=> Remove the Alpha label from Script Service V2

build/Build.Tests.cs
The nightly build for Tentacle has been intermittently failing with the error
```
The process cannot access the file because it is being used by another process
```
[sc-53315]
We identify that the test output files for both `Octopus.Tentacle.Tests` project and `Octopus.Tentacle.Tests.Integration` project are written to the same file (identical file name). This might be the reason why Tentacle build intermittently encounter the above error when trying to access that file.
`Octopus.Tentacle.Tests`
https://github.com/OctopusDeploy/OctopusTentacle/blob/73cc874c420d06dc7e77edf4a50679de7396bcce/build/Build.Tests.cs#L214C3-L214C3
`Octopus.Tentacle.Tests.Integration`
https://github.com/OctopusDeploy/OctopusTentacle/blob/73cc874c420d06dc7e77edf4a50679de7396bcce/build/Build.Tests.cs#L245C18-L245C18 …
=> Ensure test results are written to separate files

build/Build.Tests.cs
Test builds have been intermittently failing due to the "XML report processing" build feature.
> The process cannot access the file because it is being used by another process
Our investigation shows that the report files are locked concurrently within the build feature step itself so we are unable to ensure this error doesn't happen.
Hence, we'd like to remove this build feature and write the test output directly to TeamCity console.
Setting the logger to write to TC console helps remove the need of the "XML report processing" build feature.
[sc-53315]
TODO: clean up TeamCity configuration across all build template to remove the "XML report processing" build feature after this PR is merged.
=> Write test result logs to TC console

source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
Throw if cancellation is requested that way it is clear the cancellation token was triggered. Currently if the test times out early on  the `tentacle.exe` call to setup the tentacle config silently fails and so doesn't make a config file resulting in weird errors around the config file being missing. That is super hard to relate to, "the cancellation token was triggered".
[SC-56842]
```
utofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WritableTentacleConfiguration (ReflectionActivator), Services = [Octopus.Tentacle.Configuration.IWritableTentacleConfiguration], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope …
```
=> In tentacle builder throw when cancellation is requested, rather than fail for seemingly unrelated reasons.

source/Octopus.Tentacle.Client/Execution/RpcCallExecutor.cs, source/Octopus.Tentacle.Client/Observability/NonThrowingTentacleClientObserver.cs, source/Octopus.Tentacle.Client/Observability/TentacleClientObserverExtensionMethods.cs, source/Octopus.Tentacle.Client/Scripts/ScriptExecutionOrchestrator.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.CommonTestUtils/TestTentacleClientObserver.cs, source/Octopus.Tentacle.Contracts/Observability/ITentacleClientObserver.cs, source/Octopus.Tentacle.Contracts/Observability/NoTentacleClientObserver.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/TentacleClientObserver.cs, source/Octopus.Tentacle.Tests/Client/RpcCallExecutorFixture.cs
If an error occurs in the ITentacleClientObserver passed to the TentacleClient operations, it can cause Script Execution to stop and fail or throw an exception at the end of script execution / upload / download file, which is not desired.
This PR adds a decorator which will try..catch.. to ensure they do not impact the TentacleClient operations and logs a warning in the ILog so they are visible in the task log.
=> Errors in TentacleClientObserver should not stop script execution or fail TentacleClient operations

source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransferRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetriedWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionAdditionalScripts.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptArgumentsWork.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptFilesAreSent.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV2IsNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionWorksWithMultipleVersions.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs, source/Octopus.Tentacle.Tests.Integration/FileTransferServiceTests.cs, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/ScriptServiceTests.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV2IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/TentacleClientObserver.cs
In the hopes this might help reduce failures like this:
```
00:00:00.0523229 [ClientFileTransfersAreRetriedWhenRetriesAreEnabled] [FailedDownloadsAreRetriedAndIsEventuallySuccessful(Polling,6.3.417,Sync)] Test started
00:00:54.6654409 [PortForwarder] [FailedDownloadsAreRetriedAndIsEventuallySuccessful(Polling,6.3.417,Sync)] Listening on "127.0.0.1:50205"
```
In which it took `54s` to go from the test starting the the port forwarder (which is the first thing to do anything before tentacle is started) to start listening.
[SC-56842]
```
> pstacks
________________________________________________
~~~~ 83e0
1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, CancellationToken)
1 …
```
=> Reduce thread usage with a async command runner

source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.CommonTestUtils/DataStreamExtensionMethods.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV2IsNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyTentacleClientBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationTokenObservingPendingRequestQueueDecorator.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspaceFactory.cs, source/Octopus.Tentacle/Services/FileTransfer/FileTransferService.cs
[sc-53245]
As part of making Halibut async, we need to update the version of Halibut.
Note that for now we have disabled the compile errors around obsolete methods, and made cards for them on the board.
Related to https://github.com/OctopusDeploy/Issues/issues/8266
=> Updating to a newer version of Halibut

.gitignore
After pulling this repo and loading it in Rider, I noticed that `.DS_Store` files are showing up. Usually we just add `.DS_Store` to the git ignore to stop them from showing up as they are just a MacOS hidden file that we can safely ignore.
More info here: https://en.wikipedia.org/wiki/.DS_Store
=> Update git ignore to include .DS_Store files

docker-compose.yml
Change the SQL Docker image for the "Test: Windows Docker Image"
This original image gets rebuilt quite frequently and appears to be breaking when starting locally. We don't publish tagged versions so I don't think there is a way to use an older image.
Reverting to a much older docker image that Octopus publish gets us back to a working image.
In the long term, we may want to investigate why the original image has stopped working, but this removed an immediate blocker.
=> Change the SQL Docker image for the "Test: Windows Docker Image"

source/Octopus.Tentacle.Client/Execution/RpcCallExecutor.cs, source/Octopus.Tentacle.Client/Retries/RpcCallRetryHandler.cs, source/Octopus.Tentacle.Tests/Client/RpcCallRetryHandlerFixture.cs
When retries are performed, we log some information so the user can understand what is happening.
The current log message is a bit unclear about how much longer retries will occur for as it reports the total allowed retry duration which includes the time the initial call has.
This PR changes that so we report the remaining duration rather than the total allowed duration.
=> Show the remaining retry duration in rpc retry log messages

.nuke/build.schema.json, build/Build.Tests.cs, installer/Octopus.Tentacle.Installer/Product.wxs
[sc-58906]
We want to ensure our existing (net48) and new (net6.0) installers work with some automated tests.
Related to OctopusDeploy/Issues#8266
We have one existing automated test for our installers. It does actually cover both installers already. But all it tested was that the install location directory excluded a certain permission.
We now also test that `Tentacle.exe` was installed, and that it can be run (just a simple command, `help`).
**Locally**
**TeamCity**
=> Adding extra testing for both net48 and net6.0 installers

source/Octopus.Tentacle.CommonTestUtils/Builders/ScriptBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/RandomTemporaryFileBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/ListeningResponseMessageTcpKiller.cs
We would like to have full confidence in the reliability of Tentacle on older versions of Windows i.e. Windows Server 2012, 2012 R2, and 2016. As such, this PR makes some small changes to our integration test setup to ensure we get reliable test run results.
There are detailed comments below each code change in the PR, to explain why the particular change is being made.
Fixes [sc-58883]
=> Fix integration test builds on previous versions of Windows

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/EnumExtensions.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/WarmTentacleCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationTestCase.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleExeFinder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/ITentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/LinuxTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/NugetTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/TentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/VersionDependentTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/WindowsOnlyNugetBinsTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleRuntime.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleTestCaseSourceAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Util/SerilogLoggerBuilder.cs, source/Octopus.Tentacle/Util/RuntimeDetection.cs, source/Octopus.Tentacle/Util/TeamCityDetection.cs
We would like to automatically test a net6 client (i.e. Octopus Server using TentacleClient) communicating with a net48 service (i.e. Tentacle running on .NET Framework). This PR adds support for this by adding a `TentacleRuntime` enum, which is then used by the test system to automatically generate extra test cases from existing tests for this scenario.
The extra test cases will only be generated if:
- Tests are being run on **Windows**, and...
- Tests are being run using the **.NET 6.0** runtime
Test runs on other platforms (Linux, Mac) or other runtimes (.NET Framework 4.8) should be unaffected.
These extra test cases will also be tagged with the test category `Net60ClientNet48Tentacle`, which will allow us to split them into another test run if desired.
Fixes [sc-56679]
Quality …
=> Add support for testing net6.0 client (TentacleClient) with net48 service (Tentacle)

source/Octopus.Tentacle.Tests.Integration/Support/TestEnvironmentHelper.cs, source/Octopus.Tentacle.Tests.Integration/Util/RunningScriptFixture.cs, source/Octopus.Tentacle.Tests.Integration/Util/SilentProcessRunnerFixture.cs
[sc-59228]
[sc-59220]
To support Windows 2012 and Windows 2012R2, we have a build chain that tests Tentacle against this OS. But there are some tests that fail reliably.
There were consistent [test failures for 2012] (https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacle_IntegrationTestNet48onWindows2012/9512172?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true):
and [in 2012R2](https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacle_IntegrationTestNet48onWindows2012r2/9512177?hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=tru …
=> Fixing tests for 2012

build/Build.Tests.cs, build/Build.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleTestCaseSourceAttribute.cs
[Recent changes to test more combinations of server and client versions](https://github.com/OctopusDeploy/OctopusTentacle/pull/576) (i.e. net6.0 client <-> net48 service) have made our Windows (net6.0) Integration test builds take longer than we'd like.
This PR adds another build target called `TestIntegrationNet60ClientNet48Service`, which in combination with changes to the build chain in TeamCity, will allow us to split our integration test builds into separate test runs, allowing quicker and clearer feedback from the builds system.
* Existing Windows integration test builds (current, 2016, 2012 R2, 2012) take roughly the same time they have been
* New (!) Windows integration test builds for current, 2016, 2012 R2, 2012 versions i.e. `Integration Test: net6.0 on Windows (net48 service)` …
=> Add Integration Test build target for net 6.0 client <-> net48 service

build/Build.Tests.cs, build/Build.cs
It's much nicer if our custom Nuke params are named the same between Halibut and Tentacle, so this PR ensures this for the new test filter param i.e. `Filter` -> `TestFilter`
=> Rename nuke param for consistency

source/Octopus.Tentacle.Tests.Integration/Support/RetryHelper.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
Investigation [into this flakey integration test](https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacle_IntegrationTestNet60onWindows2012r2/9505956?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true) has uncovered an area of thread unsafe code in Tentacle, which can occasionally cause test failures on the build server but (thankfully) is unlikely to affect customers in production.
The [ApplicationInstanceStore](https://github.com/OctopusDeploy/OctopusTentacle/blob/8edad0d48bcd67fb408e59be1752bb1cd088e69a/source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceStore.cs) class is responsible for reading and writing instance configurations when …
=> Add RetryHelper

source/Octopus.Tentacle.Client/Execution/RpcCallExecutor.cs, source/Octopus.Tentacle.Client/Retries/RpcCallRetryHandler.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransferRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetriedWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExtensionMethods/InMemoryLogAssertionExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExtensionMethods/LogExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Support/IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/IntegrationTestTimeout.cs, source/Octopus.Tentacle.Tests.Integration/Support/RetryLogMessageAssertions.cs, source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/BumpThreadPoolForAllTests.cs, source/Octopus.Tentacle.Tests.Integration/Support/TestSerilogILoggerILog.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/TentacleClientExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Util/SerilogLoggerBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TentacleClientTestExtensionMethods.cs, source/Octopus.Tentacle.Tests/Client/DefaultScriptObserverBackoffStrategyTests.cs, source/Octopus.Tentacle.Tests/Client/PollingTentacleScriptObserverBackoffStrategyTests.cs, source/Octopus.Tentacle.Tests/Client/RpcCallExecutorFixture.cs, source/Octopus.Tentacle.Tests/Client/RpcCallRetryHandlerFixture.cs, source/Octopus.Tentacle/Diagnostics/Log.cs
Don't log that we will retry when there is no time left and reties won't be performed.
Don't log that retries have timed out if we never performed them as there was no time e.g. the initial request took longer than the retry duration.
Would log that a retry was going to be performed when there was no time left.
Would log that retries were attempted even if none were performed. 
Will not log we are about to retry when there is no time left.
Will not log that retries timed out if no retries were attempted.
=> Stop logging retry messages when retries won't actually be performed

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/WarmTentacleCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationTestCase.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleExeFinder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/NugetTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleRuntime.cs
[sc-60184]
We recently [added support for testing net6.0 client with net48 service](https://github.com/OctopusDeploy/OctopusTentacle/pull/576).
This seemed to drastically increase the number of tests run in TeamCity.
Related to OctopusDeploy/Issues#8266
TeamCity would run the tests on different test chains, for different platforms, and aggregate them together. 
As seen here, before we introduced the net6.0/net48 test cases, it ran each of these on 7 different build chains:
`TentacleConfigurationsAttribute` was then altered to try different runtimes:
```
#if NETFRAMEWORK
var runtimes = new List<TentacleRuntime> { TentacleRuntime.Default };
#else
var runtimes = PlatformDetection.IsRunningOnWindows
? new List<TentacleRuntime> {TentacleRuntime.DotNet6, TentacleRuntime.Framework48}
: new …
```
=> Removing TentacleRuntime.Default, replacing it with a calculated value

source/Octopus.Tentacle.Tests/Client/RpcCallRetryHandlerFixture.cs
Fix https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacleNet48_SensibleDefaultsChainFullChain/9675007?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
=> Fix flaky test CancelsTheExecutingActionIfItIsARetryAfterTheTimeout

build/Build.Pack.cs, source/Octopus.Tentacle.Upgrader/GlobalSuppressions.cs, source/Octopus.Tentacle.Upgrader/Octopus.Tentacle.Upgrader.csproj, source/Octopus.Tentacle.Upgrader/ServiceBouncer.cs
The Windows auto-upgrade installer (managed by Octopus Server) requires an `Octopus.Tentacle.Upgrader` file to kick off the auto-upgrade process. It requires .Net Framework to be installed on the user's machine. 
Now that we are rolling out support for .Net 6 standalone tentacles on Windows, we need to include standalone versions of the `Octopus.Tentacle.Upgrader` so that customers don't need to have .Net Framework installed on their Windows machines to allow Octopus server to install and run tentacles.
The `Octopus.Tentacle.CrossPlatformBundle` should now include two new files:
- Octopus.Tentacle.Upgrader-net6.0-win-x86.exe
- Octopus.Tentacle.Upgrader-net6.0-win-x64.exe
[sc-59761]
It should get rid of the following error when the server tries to upgrade a .Net 6 tentacle:
Quality …
=> Add support for .Net 6 Windows tentacle upgrader

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
This PR bumps Halibut to get [some more detail in our logs](https://github.com/OctopusDeploy/Halibut/pull/503), which will be useful for monitoring the Async Halibut rollout.
=> Bump Halibut to v6.0.1457

source/Octopus.Tentacle.Tests/Configuration/ApplicationInstanceSelectorFixture.cs, source/Octopus.Tentacle/Commands/RegisterMachineCommand.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceSelector.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceStore.cs, source/Octopus.Tentacle/Configuration/Instances/IApplicationInstanceStore.cs
Tentacle CLI gives the same error message for a range of failure modes, and references the OctopusServer instead of Tentacle.
The `ApplicationInstanceSelector` code was copied directly from `Octopus.Shared` when it was merged into the different codebases, and the reference to `OctopusServer` should have been removed then. 
Additionally, we used an unnecessary try-catch when handling control flow exceptions that was stripping out useful error messages so I've removed it.
When you are configuring Tentacle via the command line, have multiple instances configured, and forget to specify which instance, you get a cryptic response:
> PS C:\Program Files\Octopus Deploy\Tentacle> .\Tentacle.exe service --stop
There are no instances of OctopusServer configured on this machine. Please run the setup …
=> Minor output wording adjustments

build/Build.cs
At the moment, the `Harden-InstallationDirectory.ps1` script only gets copied to the .Net Framework installation directory, but it also needs to be available on .Net Core installer directories, now that .Net Core tentacles are supported.
Fixes [sc-61274]
The  `Harden-InstallationDirectory.ps1` script is copied over only to: 
- `_build\Tentacle\net48\win`
The  `Harden-InstallationDirectory.ps1` script is copied over to: 
- `_build\Tentacle\net48\win`
- `_build\Tentacle\net6.0\win-x86`
- `_build\Tentacle\net6.0\win-x64`
Should we have tests covering this?
=> Copy Harden-InstallationDirectory script to all possible Windows installer directories

source/Octopus.Tentacle.Tests/Commands/RunAgentCommandFixture.cs, source/Octopus.Tentacle/Commands/RunAgentCommand.cs
From @sburmanoctopus: 
> The newly introduced `WorkspaceCleanerTask`, through its dependency tree, eventually takes a dependency on the `IKeyValueStore`.
> 
> This object validates some of the configuration. So when it does that, it might not be valid (e.g. in E2E tests), and throws an exception.
> 
> This, in turn, causes the `WorkspaceCleanerTask` to also throw a dependency resolution exception.
> 
> Looking at the `RunAgentCommand` (which is what creates the cleaner task), it seems like this isn't the first time this problem has happened.
> 
> And the go-to move we have done several times in this class already is to add the dependency using a Lazy.
> 
> This allows the class to be created when its dependencies are not legit yet. Which is what we need when calling commands like 'help'. …
=> Convert IWorkspaceCleanerTask to Lazy<IWorkspaceCleanerTask>

.gitignore
I have some development scripts for registering a tentacle locally but I don't want these checked in (as they have API keys in them), so I want to ignore them
=> Ignore development scripts

build/Build.Pack.cs, build/Build.Tests.cs, build/Build.cs
If you are making changes to the Clients and Contracts libraries and want to use them locally in Server, to make this easier we add a unique timestamp and target to all Local builds.
Also adds a new Target to build and copy these two packages to the LocalPackages directory
=> Copy Client & Contracts to local packages with unique timestamped version

source/Octopus.Tentacle.Contracts/ScriptTicket.cs, source/Octopus.Tentacle.Tests/Contracts/ScriptTicketFixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs
[sc-60772]
When comparing the [ScriptService](https://github.com/OctopusDeploy/OctopusTentacle/blob/c8c61358a053365e30b6df33d0248252db6bc856/source/Octopus.Tentacle/Services/Scripts/ScriptService.cs#L11) and [ScriptServiceV2](https://github.com/OctopusDeploy/OctopusTentacle/blob/c8c61358a053365e30b6df33d0248252db6bc856/source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs), it was noticed that `ScriptService` was doing lookups on the `TaskId` of the `ScriptTicket` ignoring case. But `ScriptServiceV2` was doing lookups on the `ScriptTicket` itself (therefore using `GetHashCode`, which respects casing). These were inconsistent. 
If someone made a request of the V2 API using a `ScriptTicket` with different casing, it would not return the correct result.
Now, we ignore casing for …
=> Fixing script ticket casing equality

source/Tentacle.sln
[sc-62554]
Every time a Visual Studio user would open the Tentacle solution, VS would alter it.
If the unsuspecting VS user was not paying attention, this change would often make its way into a PR, and the build server would no longer compile. Often leaving the poor VS developer confused about what they did wrong.
We applied to same fix as [this PR](https://github.com/OctopusDeploy/Halibut/pull/512) for Halibut.
=> Fix Solution for VS Users and Nuke

source/Octopus.Tentacle.CommonTestUtils/Builders/StartScriptCommandV3AlphaBuilder.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV3AlphaFixture.cs, source/Octopus.Tentacle/Maintenance/WorkspaceCleaner.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV3Alpha/IAsyncScriptServiceV3Alpha.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV3Alpha/ScriptServiceV3Alpha.cs
Following on from #635, this PR adds the implementation of `ScriptServiceV3Alpha`. This is a direct copy of the `ScriptServiceV2` class, with modifications to support the async methods.
I added the `IAsyncScriptServiceV3Alpha` in the same assembly as the implementation as it's not part of the "public" contract, just an internal contract.
I hooked up the new service into the `WorkspaceCleaner`.
I duplicated the `ScriptServiceV2Fixture` and `StartScriptCommandV2Builder` to verify that the new V3 implementation works identically to the existing V2 implementation
Note: It does mean any changes to `ScriptServiceV2` will need to be propagated to `V3Alpha`
Shortcut story: [sc-62810]
=> Add ScriptServiceV3Alpha implementation

source/Octopus.Tentacle.Client/Decorators/HalibutExceptionCapabilitiesServiceV2Decorator.cs, source/Octopus.Tentacle.Client/Decorators/HalibutExceptionExtensions.cs, source/Octopus.Tentacle.Client/Decorators/HalibutExceptionScriptServiceV2Decorator.cs, source/Octopus.Tentacle.Client/Decorators/HalibutExceptionTentacleServiceDecorator.cs, source/Octopus.Tentacle.Client/Decorators/HalibutExceptionTentacleServiceDecoratorFactory.cs, source/Octopus.Tentacle.Client/ITentacleServiceDecoratorFactory.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs
In preparation for adding the ScriptServiceV3Alpha to TentacleClient, this PR just cleans up some duplicate code around the halibut exception decorators.
- Renamed `ITentacleServiceDecorator` to `ITentacleServiceDecoratorFactory` (as well as implementations) to make it clear that it's not a decorator itself, but creates decorators
- Added a new abstract `HalibutExceptionTentacleServiceDecorator` to consolidate the exception handling logic and to reduce code reuse
- Move all decorators to their own files (but co-located the sync/async versions of the decorators)
Shortcut story: [sc-62862]
=> Cleanup the halibut exception decorators

source/Octopus.Tentacle.Tests/Integration/ScriptLogFixture.cs, source/Octopus.Tentacle/Services/Scripts/ScriptLog.cs
[SC-63899]
Fixes a bug where calls to `GetStatus` would fail when a script log line was corrupt e.g. incomplete because tentacle was killed while writing the logs for a running script.
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/655
Previously the call to `GetStatus` would fail and no further logs could be read.
The call to `GetStatus` will succeed, and we will read up to but not including the corrupt log line.
We do report the fact that the log was corrupt.
=> When a scripts tentacle log is corrupt, return all valid logs up to the corrupted log line.

source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs
Minor tweak to change the `PollingTentacleBuilder` to use the correct logging context
=> Change to "PollingTentacleBuilder" logging context to match class

source/Octopus.Tentacle.Client/Scripts/ScriptOrchestratorFactory.cs, source/Octopus.Tentacle.CommonTestUtils/DataStreamExtensionMethods.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetriedWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/FileTransferServiceTests.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationTokenObservingPendingRequestQueueDecorator.cs, source/Octopus.Tentacle.Tests/Capabilities/CapabilitiesServiceV2Fixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceFixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs, source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Communications/HalibutInitializer.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Scripts/IScriptWorkspaceFactory.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspaceFactory.cs, source/Octopus.Tentacle/Services/Capabilities/CapabilitiesServiceV2.cs, source/Octopus.Tentacle/Services/Capabilities/IAsyncCapabilitiesServiceV2.cs, source/Octopus.Tentacle/Services/FileTransfer/FileTransferService.cs, source/Octopus.Tentacle/Services/FileTransfer/IAsyncFileTransferService.cs, source/Octopus.Tentacle/Services/Scripts/IAsyncScriptService.cs, source/Octopus.Tentacle/Services/Scripts/IAsyncScriptServiceV2.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV3Alpha/ScriptServiceV3Alpha.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
Sync operations have been removed from Halibut in favour of Async operations. 
This PR updates the version of Halibut used in the Tentacle solution to one with Sync Halibut removed.
This PR also changes Tentacle to support only Async Halibut and updates the Services implemented in Tentacle to use the Async Service Contract along with modifications to the implementation to use async methods where it makes sense.
The Tentacle solution has all Sync Halibut operations removed.
Related to OctopusDeploy/Issues#8266
[sc-58528]
[sc-56576]
- Automated testing / Exploratory testing / Nothing required?
- Is the build green?
=> Removing Sync Halibut from Tentacle 

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationTestCase.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/Proxies/MethodUsageProxyDecorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilderExtensions.cs
As we test more versions of TentacleClient against older versions of Tentacle, we need to adjust the tests to know which script service is running on the target version of tentacle, so we can correctly test that version.
Adds a new static mapping of Tentacle Version -> Latest script service type supported on that version of tentacle. This is then included in the `TentacleConfigurationTestCase`.
I added an overload to the `RecordMethodUsages` extension method to create the dynamic proxy given a type (rather than a generic parameter).
I updated 2 tests to use this new logic.
Shortcut story: [sc-62862]
=> Test against known latest script service on Tentacle

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Services/FileTransfer/FileTransferService.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
[sc-45141]
Updating Tentacle and Tentacle Client to use TCP Keep Alives, as well as adding an option to turn this on for Tentacle.
=> Adding option to enable TCP keep alives in Tentacle

source/Octopus.Tentacle.Tests.Integration/ScriptServiceV3AlphaIntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleVersions.cs
If a test was using the `[TentacleConfigurations]` without explicitly including other versions of Tentacle, it would only run against the latest Tentacle. 
The latest tentacle has ScriptServiceV3Alpha, this resulted in a number of tests such as `ClientScriptExecutionRetriesTimeout` now only testing ScriptServiceV3Apha and not ScriptServiceV2 leaving significant code paths in TentacleClient untested.
This PR changes the default `[TentacleConfigurations]` to run against
- Latest Tentacle (build from source code)
- v7.1.189 which is the latest Tentacle with Sync Halibut and without ScriptServiceV3Alpha
- v8.0.81 which is the latest Tentacle with Async Halibut and without ScriptServiceV3Alpha
This will result in an increase in Tests run in the Halibut Build Chain
=> Ensure test coverage of ScriptServiceV2 now ScriptServiceV3Alpha has been added

source/Octopus.Tentacle.Tests.Integration/Startup/WindowsServiceConfiguratorFixture.cs, source/Octopus.Tentacle/Diagnostics/EventLogTarget.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Startup/CheckServicesCommand.cs, source/Octopus.Tentacle/Startup/WindowsServiceAdapter.cs, source/Octopus.Tentacle/Startup/WindowsServiceConfigurator.cs, source/Octopus.Tentacle/Startup/WindowsServiceHost.cs
Upgrade System.ServiceProcess.ServiceController library and required dependencies. 
There was a [CVE](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-24112) in the version of the library we were using. 
Had to decorate some of the Windows-specific code with compiler warning suppressions. Due to targeting .NET Framework in Tentacle, we can't use the slightly cleaner `[SupportedOSPlatform("Windows")]` Attribute instead of the warning suppression.
The changes primarily focus on the `EventLog` code - this is a log sink used only on Windows. We've tested it by building and running Tentacle via the CLI on a Windows machine and can see that it is successfully logging. 
Other than needing to add the platform-specific handling, no other changes were required for the upgrade.
There …
=> Upgrade System.ServiceProcess.ServiceController library

docker/linux/scripts/configure-tentacle.sh
Part of #project-k8s-agent
I missed this change as part of updating tentacle to better handle container restarts in kubernetes: https://github.com/OctopusDeploy/OctopusClients/pull/802
This change basically makes it so that when the container is registering itself as a kubernetes cluster, it won't use the `--force` flag. This aligns with the PR above where, now registering a kubernetes tentacle doesn't require the --force flag to register successfully, even if the tentacle is already registered.
[sc-60420]
=> Update force option so it's not applied to register-k8s-cluster

source/Octopus.Tentacle.Contracts/ScriptServiceV3Alpha/StartScriptCommandV3Alpha.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV3AlphaFixture.cs, source/Octopus.Tentacle/Maintenance/WorkspaceCleaner.cs, source/Octopus.Tentacle/Scripts/Bash.cs, source/Octopus.Tentacle/Scripts/IRunningScript.cs, source/Octopus.Tentacle/Scripts/IScriptExecutor.cs, source/Octopus.Tentacle/Scripts/IScriptExecutorFactory.cs, source/Octopus.Tentacle/Scripts/IShell.cs, source/Octopus.Tentacle/Scripts/LocalShellScriptExecutor.cs, source/Octopus.Tentacle/Scripts/PowerShell.cs, source/Octopus.Tentacle/Scripts/RunningScript.cs, source/Octopus.Tentacle/Scripts/ScriptExecutorFactory.cs, source/Octopus.Tentacle/Services/Scripts/IAsyncScriptServiceV3Alpha.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV3Alpha.cs, source/Octopus.Tentacle/Services/ServicesModule.cs
We need a way to abstract the execution of a script so we can support Kubernetes Jobs as a script execution mechanism in `ScriptServiceV3Alpha`
This PR adds 3 new interfaces and some derived implementations
`IScriptExecutor` -> Represents a distinct way to execute a script
`IScriptExecutorFactory` -> A factory that constructs/returns an IScriptExecutor
`IRunningScript` -> Represents a running script
The intent is that there will be a `KubernetesJobScriptExecutor` and a `KubernetesJobRunningScript` implementations that will be used when the script is being executed via k8s jobs.
Shortcut story: [sc-61762]
=> Abstract script execution in ScriptServiceV3Alpha

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/Server.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/TentacleCommandLineTests.cs
[Server E2E Tests contain](https://github.com/OctopusDeploy/OctopusDeploy/blob/b05682cda766c915af18eac21f6c3a9b35468756/source/Octopus.E2ETests.API/Scripts/CommandLineInterface/TentacleCommandLineInterfaceTestScript.cs#L31) a set of tests that ensure the Tentacle command line works as expected. As these tests are in the Server build chain, it was possible to break the Tentacle command line and only discover this sometime later when that version of Tentacle is updated in Server.
This PR moves those tests to the OctousTentacle repo so regressions cannot be introduced into the Tetnacle solution.
https://github.com/OctopusDeploy/OctopusDeploy/pull/21424 will remove the tests from the Server E2E tests
[sc-61799]
The following tests have been copied from …
=> Migrate Tentacle command line tests from Octopus E2ETests

source/Octopus.Tentacle.Tests.Integration/Support/OctopusPackageDownloader.cs
We are seeing timeouts downloading tentacle binaries 
```
OneTimeSetUp: System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
----> System.TimeoutException : The operation was canceled.
----> System.Threading.Tasks.TaskCanceledException : The operation was canceled.
----> System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
----> System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
```
This PR bumps the allowed time to see if it can reduce the occurrence of hte issue.
=> Allow more time to download tentacle binaries

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
[sc-42848]
While enhancing all the timeouts and limits within Halibut, we wanted to be able to try them out before making them the permanent defaults. 
The existing timeouts are retained, so that we can simply keep using them while we test out these values.
We now have an environment variable that allows us to use the recommended values and limits.
=> Adding environment variable to use recommended timeouts and limits

source/Octopus.Tentacle.Tests.Integration/Util/TestUserPrincipal.cs, source/Octopus.Tentacle.Tests/Util/TestUserPrincipal.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Remove implicit dependencies on `System.Drawing.Common` to address [CVE-2021-24112](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-24112). This is achieved by updating the following references in `Octopus.Tentacle` to the latest versions:
* `System.Diagnostics.EventLog` (7.0.0 -> 8.0.0)
* `System.DirectoryServices.AccountManagement` (5.0.0 -> 8.0.0)
* `System.Security.Cryptography.ProtectedData` (4.5.0 -> 8.0.0)
There is a [CVE ](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-24112) lodged against the version of `System.Drawing.Common` being referenced.
Partially fixes [Upgrade all usages of System.Drawing.Common in Tentacle](https://github.com/OctopusDeploy/OctopusTentacle/issues/689).
The following will be completed in future PRs to fully address the CVE: …
=> Update Octopus.Tentacle dependencies to mitigate System.Drawing.Common CVE

source/Octopus.Tentacle.Tests.Integration/Startup/LinuxConfigureServiceHelperFixture.cs, source/Octopus.Tentacle.Tests.Integration/Support/TestAttributes/RequiresSudoOnLinuxAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Util/OctopusPhysicalFileSystemFixture.cs
Add a test category and apply to tests that require sudo on Linux.
This will allow these tests to be filtered out of integration test runs on agents where tests cannot run as Sudo
=> Add a test category and apply to tests that require sudo on Linux

build-k8s-docker-local.ps1, docker/kubernetes-tentacle/Dockerfile, docker/kubernetes-tentacle/scripts/configure-tentacle.sh
The Kubernetes Tentacle needs to be able to configure the directory path for the home + application directories so they can be specified to be on a NFS/volume mount 
The container now takes the `TentacleHome` and `TentacleApplications` environment variables and uses them in `configure-tentacle.sh` if they are set to override the default values.
We also now explicitly set the `home` directory in the `create-instance` command (for clarity).
Also some minor bash cleanups: `! -z` is the same as `-n`
Shortcut story: [sc-66137]
=> Support overriding configuration directories in K8s Container

build-k8s-docker-local.ps1, source/Octopus.Tentacle/Configuration/Crypto/LinuxGeneratedMachineKey.cs, source/Octopus.Tentacle/Configuration/Crypto/MachineKeyEncryptor.cs, source/Octopus.Tentacle/Util/PlatformDetection.cs
The machine key is currently generated for linux in `/etc/octopus/machinekey`. This then is _regenerated_ when the pod restarts, so the encrypted values (which are stored in the home directory, on a NFS share) can't be decrypted
When running in K8S only, we change the location of the file to generate the machine key to be in the configured environment variable `TentacleHome` (which currently is the NFS share `/octopus`). This results in the key being persisted across pod restarts and the cert can be decrypted
Shortcut story: [sc-66137]
=> Generate machine key in home directory in K8s

source/Octopus.Tentacle/Octopus.Tentacle.csproj
To help re-registration/pod restarts in K8s, we need to include some changes to `Octopus.Client`
The relevant PR for the version change 
https://github.com/OctopusDeploy/OctopusClients/pull/802
Shortcut story: [sc-60420]
=> Bump Octopus.Client to 14.3.1013

source/Octopus.Tentacle/Scripts/Kubernetes/RunningKubernetesJobScript.cs
When running in K8s, we don't actually have an instance name in the home directory (as there is only one instance). The existing job code assumed there would be an instance name under the home directory
Removes the instance name from relevant paths
Shortcut story: [sc-66137]
=> Remove instance name from K8s Job file paths

source/Octopus.Tentacle.Tests.Integration/Support/OctopusPackageDownloader.cs
We are seeing time outs when downloading older tentacle versions, where the timeout is set to 150s.
This PR attempts to help with that by:
* Reducing the timoeut to 20s, since the timeout appears to apply to each read/write rather than the operation as a whole.
* Attempt 5 times (with a simple for loop since the problem we have is a timout of 20s to read any bytes so we probably don't have a reason to get fancy).
=> Attempt to download tentacles multiple times

source/Octopus.Tentacle.Tests/Communications/TentacleCommunicationsModuleFixture.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs
Enable Halibut TCP Keepalives by default
The environment variable has been left so that TCP keep alive can be disabled if required.
[sc-64824]
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/692
=> Enable Halibut TCP Keepalives by default

source/Octopus.Tentacle.Tests/Communications/TentacleCommunicationsModuleFixture.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs
Reverts OctopusDeploy/OctopusTentacle#714 which results in Tcp KeepAlives being enabled by default.
TcpKeep Alives were reverted as it was thought it may be causing issues stopping and starting Tentacle on Dynamic Workers.
This issue was actually found to have been introduced with Async Halibut https://github.com/OctopusDeploy/OctopusTentacle/pull/716
[sc-64824]
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/692
=> Enable Halibut TCP Keepalives by default! Again!!

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs
Test the tentacle client with recommended halibut timeouts, since we are about to use those in Octopus Server.
[[SI-65621]]
=> Test tentacle client with recommended timeouts, like in Octopus

source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/TurnOnTraceLoggingForLogFileForLatestTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/TentacleIntegrationSetupFixtures.cs, source/Octopus.Tentacle.Tests.Integration/TentacleStartupAndShutdownTests.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/TentacleClientExtensionMethods.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Configuration/ProxyConfigParser.cs, source/Octopus.Tentacle/Services/FileTransfer/FileTransferService.cs
Fix a bug where Tentacle does not dispose of the HalibutRuntime on shutdown.
This can result in the listening port for a listening tentacle not being freed up quickly and stop the tentacle service from being stopped and started quickly.
The HalibutRuntime only had a DisposeAsync method, Dispose has also been added so it works correctly with the version of Autofac used in Tentacle.
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/725 
[sc-66309]
=> Bump Halibut so HalibutRuntime is Disposed correctly on Tentacle Shutdown

source/Octopus.Tentacle.Tests.Integration/ClientFileTransferRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceNonV1IsNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExceptionContract.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExceptionContractAssertionBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExceptionContractAssertionBuilderExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Support/FailureScenario.cs
=> Test Exception Contracts for Tentacle Client

source/Octopus.Tentacle.Tests.Integration/MachineConfigurationHomeDirectoryTests.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/TentacleCommandLineTests.cs, source/Octopus.Tentacle.Tests/Configuration/ApplicationInstanceStoreFixture.cs, source/Octopus.Tentacle.Tests/Startup/CheckServicesCommandFixture.cs, source/Octopus.Tentacle.Tests/Startup/WatchdogCommandFixture.cs, source/Octopus.Tentacle/Configuration/ApplicationName.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceStore.cs, source/Octopus.Tentacle/Configuration/ServiceName.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
Allow the MachineConfigurationHomeDirectory to be changed and use a unique directory per test to isolate cross test issues
[sc-66742]
=> Allow the MachineConfigurationHomeDirectory to be changed and use a unique directory per test to isolate cross test issues

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ExtensionMethods/ScriptExecutionResultExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/TentacleStartupAndShutdownTests.cs, source/Octopus.Tentacle.Tests.Integration/WorkspaceCleanerTests.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV3AlphaFixture.cs, source/Octopus.Tentacle/Scripts/IScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspace.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs
Adding some more logging to a flakey test `WhenScriptServiceIsRunning_ThenWorkspaceIsNotDeleted` e.g. https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacleNet48_SensibleDefaultsChainFullChain/10569176?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildTestsSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=false
Removed a sync call that then did a Wait on an async call as well can be fully async now.
[sc-66742]
=> Additional Logging for Flakey Workspace Cleanup Test and removal of Sync over Async while deleting a workspace

source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceStore.cs
Set Environment variables for the Windows and Linux Service so it behaves like running Tentacle via the console in tests.
The tests were already flakey and then broken with https://github.com/OctopusDeploy/OctopusTentacle/pull/738 
No muted tests with the last run of this PR so looking like it has solved the main issues
I can still get failures on Ubuntu locally if I run to failure, so it's not 100% reliable but it shifts the issue on to the restart `--stop --start` performed during the test, rather than the failure occurring when trying to setup and start the service initally.
=> Fix Tests that start Tentacle as a Service

source/Octopus.Tentacle.Tests.Integration/WorkspaceCleanerTests.cs
The test `WhenScriptServiceIsRunning_ThenWorkspaceIsNotDeleted` was written to ensure that a running script did not have it's workspace cleaned up by the background cleanup job while it was still running / not completed.
The test then went on to verify that the workspace was cleaned up when CompleteScript was called. This turns out to be somewhat flakey as the `CompleteScript` call does a best effort attempt to delete the workspace before silently failing!!
While it would be nice to have a reliable test that asserts that complete script always cleans up the workspace it seems the code to try and silently fail is by design and the intent of this test was to make sure the workspace isn't unexpectedly deleted by the background cleanup job.
Test has been modified to remove the assertion that …
=> Fix flakey WhenScriptServiceIsRunning_ThenWorkspaceIsNotDeleted test

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/Support/IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Util/Wait.cs, source/Octopus.Tentacle.Tests.Integration/WorkspaceCleanerTests.cs
Possible fix for Execution Timeout issues seen on Build Server
- Wait.For now requires a specific timeout to avoid waiting for too long / never finishing the wait if the CancellationToken fails to be cancelled
- IntegrationTest will now attempt to cancel the cancellation token just before the test times out. Nunit does not call TearDown on the test if it times out through the `TimeoutAttribute` so we end up in a state where the CancellationToken used for test cleanup is not cancelled and things can keep running.
=> Possible fix for Execution Timeout issues seen on Build Server

source/Octopus.Tentacle.Tests.Integration/ClientFileTransferRetriesTimeout.cs
This test was failing by somehow successfully as far as the caller is concerned, uploading the file to tentacle.
Looking at the logs we see on the second attempt to upload the file:
```
00:00:04.4086383 [TentacleClient] [WhenRpcRetriesTimeOut_DuringUploadFile_TheRpcCallIsCancelled(Listening,Latest,True)] Info "Beginning upload of UploadFile.txt to Tentacle"
12/16/2023 5:33:18 AM 228 Info Beginning upload of UploadFile.txt to Tentacle
00:00:04.4087075 [MethodLoggingProxyDecorator] [WhenRpcRetriesTimeOut_DuringUploadFile_TheRpcCallIsCancelled(Listening,Latest,True)] IAsyncClientFileTransferService.UploadFileAsync() started
00:00:04.4087428 [ClientFileTransferRetriesTimeout] [WhenRpcRetriesTimeOut_DuringUploadFile_TheRpcCallIsCancelled(Listening,Latest,True)] Killing PortForwarder …
```
=> Remove race condition in WhenRpcRetriesTimeOut_DuringUploadFile_TheRpcCallIsCancelled

source/Octopus.Tentacle/Scripts/ScriptWorkspace.cs
Try and make ScriptWorkspace.Delete more reliable
It appears that the FileSystem.DeleteDirectory method can fail to delete the directory in cases where Directory.Delete(recursive: true) can be successful.
Leaving the existing code as we would need to understand more about the intent of the logic before changing it but adding in another best effort attempt to delete the directory.
This has been observed in Workspace Cleaner tests
=> Try and make ScriptWorkspace.Delete more reliable

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
Fix the LegacyClientAndTentacleBuilder not using a custom Machine configuration home directory
=> Fix the LegacyClientAndTentacleBuilder not using a custom Machine configuration home directory

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
Work around an issue where Tentacle configuration, startup and removal cannot be isolated in integration tests for Tentacle < 8.1.284
This can lead to tests colliding and failing due to misconfiguration or incorrect startup/failure of Tentacle.
=> Work around an issue where Tentacle configuration, startup and removal cannot be isolated in integration tests for Tentacle < 8.1.284

.nuke/build.schema.json, build-k8s-docker-local.ps1, build/Build.Pack.cs, build/Build.cs, linux-packages/packaging-scripts/unsigned/create-linux-packages.sh, linux-packages/packaging-scripts/unsigned/package.sh
Because the Kubernetes Tentacle has to run in a container, we need to update the local build process to build unsigned linux artifacts and create the container using them
I duplicated the linux build scripts into a new `unsigned` subfolder and just removed all the signing logic.
I also added a new parameter `RuntimeId` to the build process so you can specific a specific runtime to build (rather than all of them).
I also updated the `build-k8s-docker-loca.ps1` script to run the nuke build, then use the correct artifact to create the container. It also contains logic to automatically push the container to the minikube registry if it's enabled. (based on https://minikube.sigs.k8s.io/docs/handbook/registry/)
```Setting kubectl context to 'minikube'
Switched to context "minikube".
Forwarding …
```
=> Support locally building unsigned Linux packages

source/Octopus.Tentacle.Client/ExceptionExtensionMethods.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV2Orchestrator.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV3AlphaOrchestrator.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PendingRequestQueueFactories/CancelWhenRequestQueuedPendingRequestQueueFactory.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/Proxies/MethodUsages.cs
Related to: https://github.com/OctopusDeploy/Issues/issues/8535
Given ScriptExecution has started for a Polling Tentacle that has recently gone offline
And the GetCapabilities response is cached
And RPC retries have started for the StartScript Call 
When the ScriptExecution is cancelled
Then TentacleClient will try and cancel script execution on Tentacle by calling CancelScript
In this scenario, we can guarantee that StartScript has never been transferred to Tentacle so the script is definitely not running.
Tentacle Client should be able to cancel any queued request and immediately return.
Cancelling ScriptExecution would start trying to cancel the script on Tentacle by calling CancelScript
Cancelling ScriptExecution does not try and call CancelScript on Tentacle and instead cancels the …
=> Cancel ScriptExecution without calling CancelScript when the StartScript request has never been transferred to Tentacle

source/Octopus.Tentacle.Contracts/Legacy/AssemblyMappingSerializationBinderDecorator.cs, source/Octopus.Tentacle.Contracts/Legacy/MessageSerializerBuilderExtensionMethods.cs, source/Octopus.Tentacle.Contracts/Legacy/NamespaceMappingSerializationBinderDecorator.cs, source/Octopus.Tentacle.Contracts/Legacy/ReMappedLegacyTypes.cs, source/Octopus.Tentacle.Tests/Contracts/Legacy/AssemblyMappingSerializationBinderDecoratorFixture.cs, source/Octopus.Tentacle.Tests/Contracts/Legacy/NamespaceMappingSerializationBinderDecoratorFixture.cs
While running simulations when deploying to 20k targets we found that process dumps would often show threads in 
```
8 Octopus.Tentacle.Contracts.Legacy.ReMappedLegacyTypes..ctor(String[])
8 Octopus.Tentacle.Contracts.Legacy.NamespaceMappingSerializationBinderDecorator..ctor(ISerializationBinder, String, String)
8 Octopus.Tentacle.Contracts.Legacy.MessageSerializerBuilderExtensionMethods.AddLegacyContractSupportToJsonSerializer(JsonSerializerSettings)
8 Octopus.Tentacle.Contracts.Legacy.MessageSerializerBuilderExtensionMethods+<>c.<WithLegacyContractSupport>b__2_0(JsonSerializerSettings)
8 Halibut.Transport.Protocol.MessageSerializerBuilder+<>c__DisplayClass11_0.<Build>g__StreamCapturingSerializer|1()
8 Halibut.Transport.Protocol.MessageSerializer+<WriteMessageAsync>d__11<System.__Canon>.M …
```
=> Cache ReMappedLegacyTypes since we found threads spending time re-creating these under high load.

source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManager/TentacleManagerModel.cs, source/Octopus.Tentacle.Tests/Commands/DeregisterMachineCommandFixture.cs, source/Octopus.Tentacle.Tests/Commands/DeregisterWorkerCommandFixture.cs, source/Octopus.Tentacle.Tests/Configuration/ApplicationInstanceSelectorFixture.cs, source/Octopus.Tentacle.Tests/Configuration/CurrentRoundTripTestBase.cs, source/Octopus.Tentacle.Tests/Configuration/InMemoryKeyValueStoreFixture.cs, source/Octopus.Tentacle.Tests/Configuration/RoundTripTestBaseFixture.cs, source/Octopus.Tentacle.Tests/Configuration/XmlFileKeyValueStoreFixture.cs, source/Octopus.Tentacle/Commands/ShowConfigurationCommand.cs, source/Octopus.Tentacle/Configuration/ConfigurationModule.cs, source/Octopus.Tentacle/Configuration/FlatDictionaryKeyValueStore.cs, source/Octopus.Tentacle/Configuration/HierarchicalDictionaryKeyValueStore.cs, source/Octopus.Tentacle/Configuration/HomeConfiguration.cs, source/Octopus.Tentacle/Configuration/IKeyValueStore.cs, source/Octopus.Tentacle/Configuration/IWritableKeyValueStore.cs, source/Octopus.Tentacle/Configuration/InMemoryKeyValueStore.cs, source/Octopus.Tentacle/Configuration/Instances/AggregatedKeyValueStore.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceConfiguration.cs, source/Octopus.Tentacle/Configuration/Instances/IAggregatableKeyValueStore.cs, source/Octopus.Tentacle/Configuration/JsonHierarchicalConsoleKeyValueStore.cs, source/Octopus.Tentacle/Configuration/KeyValueStoreBase.cs, source/Octopus.Tentacle/Configuration/PollingProxyConfiguration.cs, source/Octopus.Tentacle/Configuration/ProtectionLevel.cs, source/Octopus.Tentacle/Configuration/ProxyConfiguration.cs, source/Octopus.Tentacle/Configuration/TentacleConfiguration.cs, source/Octopus.Tentacle/Configuration/XmlFileKeyValueStore.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
As part of #project-k8s-agent, I was adding the ability for Tentacle to save and source configuration from a configmap. During this work, I found that the `Octopus.Configuration` project has been merged back into `Octopus.Server` and the repo in github has been archived.
This PR just removes the now defunct nuget package and moves the two interfaces and one enum into Tentacle. It's a relatively simple change, but it touches quite a few files to remove the old namespace.
=> Move Octopus.Configuration interfaces and enum into tentacle and update references

build/Build.Pack.cs
The nuke build doesn't work correctly on M1 macs because the DockerTasks try and pull an arm64 version of the container which doesn't exist. This change just forces the DockerTasks to use an amd64 version of the container which runs via Rosetta 2 and works correctly.
This only affects builds on machines running on arm64 architecture and all it does is set the `platform` option to `amd64`.
=> Force DockerTasks to run with image platform amd64 when running on arm64 arch

source/Octopus.Tentacle.Contracts/ScriptServiceV3Alpha/KubernetesJobScriptExecutionContext.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesSecretService.cs, source/Octopus.Tentacle/Kubernetes/Scripts/KubernetesJobScriptExecutor.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs
For certain steps (namely the Kubernetes Script Step), the customer needs to provide a Execution/Action Container to run the script in.
Server provides this information as part of the `KubernetesJobScriptExecutionContext`, which can then be used.
Kubernetes needs a secret in a specific docker config format to pull from private registries. If the user has provided a feed url & feed username, we create a secret with a unique name (which is a hash of the url domain & username) and create the correct data format.
We then use this in the `ImagePullSecrets` item in the job spec.
Shortcut story: [sc-67356]
=> Support using custom container for Kubernetes Job

source/Octopus.Tentacle.Client/Scripts/ScriptServiceV2Orchestrator.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV3AlphaOrchestrator.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV2IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV3AlphaIntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/ScriptServiceV3DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs
[SC-68685]
The tentacle client had a bug in which it would not wait longer than 1 min to wait for the response to `CompleteScriptAsync`. This meant that although Tentacle would (assuming no errors occure on tentacle itself) complete the clean up. The tentacle client would report that the cleanup was failed to be cleaned up.
Fixes: https://github.com/OctopusDeploy/OctopusTentacle/issues/770
Relates to: https://github.com/OctopusDeploy/OctopusTentacle/pull/767
We now don't set a 1 min timeout when waiting for the `CompleteScriptAsync` to complete, instead the normal Halibut timeouts will apply.
Now when a call to `CompleteScriptAsync` takes a couple of minutes, we will wait for the RPC and we will NOT report it failed (unless it actually did).
This fixes both v2 and v3Alpha Script …
=> Client should wait for script cleanup call

source/Octopus.Tentacle.Client/ITentacleServiceDecoratorFactory.cs, source/Octopus.Tentacle.Tests.Integration/Support/TestDecoratorsAreCalledInTheCorrectOrder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/CapabilitiesServiceV2DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/CombiningTentacleServiceDecoratorFactory.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/FileTransferServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/ScriptServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/ScriptServiceV2DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs
https://github.com/OctopusDeploy/OctopusTentacle/pull/663 replaced all decorators with a generic proxy decorator. That works great for things like logging ALL calls or counting ALL calls. However it is very difficult to use when the test needs to do something special with one call because:
* The proxy decorator has no autocompletion making it hard to tab your way through.
* The proxy decorator has no type safety.
* The proxy decorator assumes each RPC has exactly one parameter.
The change here is to add back some of the original test decorators, specifically it adds back the decorators that allow of doing something before/after a specific method. The result is:
* Decorations that want to apply to all calls is automatically done through the proxy decorator.
* Decorations that want to apply …
=> Add back non generic test decorators

build-k8s-docker-local.ps1, docker-compose.build-dev.yml, docker/kubernetes-tentacle/dev/Dockerfile, docker/kubernetes-tentacle/dev/scripts/bootstrap.sh, docker/kubernetes-tentacle/dev/scripts/start-debugger.sh
Updates the `build-k8s-docker-local.ps1` script with a new parameter to create a version of the Kubernetes Tentacle container with the Rider SSH debugging tools installed. https://www.jetbrains.com/help/rider/SSH_Remote_Debugging.html
There is also a new `-SkipBuild` parameter for skipping the dotnet build if you are just making revisions on the container (and don't need to build the code each time)
=> Create debug container with Rider debugging tools

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesJobService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesSecretService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesService.cs
Let's make sure that all Kubernetes objects created have the correct namespace set as well as has metadata so that it's included in the helm release (so we don't have left over resources when the helm chart is uninstalled)
=> Add standard metadata to all created Kubernetes objects

source/Octopus.Tentacle.Tests/Configuration/ApplicationInstanceSelectorFixture.cs, source/Octopus.Tentacle/Configuration/ConfigurationModule.cs, source/Octopus.Tentacle/Configuration/Crypto/KubernetesMachineKeyEncryptor.cs, source/Octopus.Tentacle/Configuration/Crypto/MachineKeyEncryptor.cs, source/Octopus.Tentacle/Configuration/Instances/ConfigMapKeyValueStore.cs, source/Octopus.Tentacle/Kubernetes/KubernetesSecretService.cs
Part of #project-k8s-agent
In the recent PR #674 I updated tentacle to allow it to store it's configuraiton in a kubernetes configmap instead of a file. This bypassed any machine key encryption which is what this PR adds.
We need to encrypt certain items that are added to the configuration store using a machine key which is generated when the tentacle is first configured.
We're adding the `KubernetesSecretService` 🕵️ to provide access to kubernetes secrets so we can store the machine key there.
=> Add encryption to configmap store

source/Octopus.Tentacle/Kubernetes/KubernetesService.cs
Turns out these were null, not empty as expected
=> Fix NRE when setting standard Kubernetes object metadata

docker/kubernetes-tentacle/dev/Dockerfile
This Dockerfile is for creating a debuggable kubernetes tentacle image.
We realised this was a copy paste error when looking into another issue so just a quick fix up.
Now the dev scripts have execution set correctly
=> Fix chmod for dev-scripts

source/Octopus.Tentacle.Tests.Integration/Support/TentacleTestCaseSourceAttribute.cs
Integration tests which test with an older version of tentacle are now categorised with `TentacleBackwardsCompatibility`.
Doing so will make it possible to not test this category on some teamcity OS VM agents.
[SC-65861]
=> Adds a TentacleBackwardsCompatibility test category

build/test-scripts/integration/common/run-integration-tests-on-vm-agents.sh
[SC-65861]
The integration test scripts for VMs now supports running tests with sudo, since some VMs have users with sudo access. This means we can run Integration tests that require sudo in those cases.
=> Run Integration Tests Script for VMs supports sudo

build/test-scripts/integration/common/run-integration-tests-on-vm-agents.sh
[SC-65861]
To avoid needing VMs to have old ssl libs installed, this stops testing on VMs only that compatibility with old tentacles is maintained.
=> Don't run Tentacle Compatibility tests with VMs

source/Octopus.Tentacle.Tests.Integration/Startup/WindowsServiceConfiguratorFixture.cs, source/Octopus.Tentacle.Tests.Integration/Support/TestAttributes/RequiresAdminOnWindowsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Util/RunningScriptFixture.cs, source/Octopus.Tentacle.Tests.Integration/Util/SilentProcessRunnerFixture.cs
Removes the creation of a windows user from some tests since, it wasn't required.
Adds a `[RequiresAdminOnWindows]` test attribute for integration tests which require admin on windows.
Doing this means the windows build can be run in containers and the windows VM builds wont need to run with old versions of tentacles.
=> Add RequiresAdminOnWindows Attribute, and dont make test users when we don't need to.

source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs
[sc-70260]
The agent doesn't need to keep a journal, since the journal is intended for long-lived extracted files that are used externally AFTER deployment has completed.
=> Disable journalling on Kubernetes Agent scripts - there's no need for it

linux-packages/content/configure-tentacle.sh
[SC-68270]
Fixes: https://github.com/OctopusDeploy/OctopusTentacle/issues/793
Related to: https://github.com/OctopusDeploy/OctopusTentacle/issues/527
The script would always assume `10943` as the comms port.
It now asks if the comms port is at the same or different address:
```
Is the comms port on the same domain as the Octopus Server : 1) Yes or 2) No (default 1): 2
What is the Octopus Server comms address including port e.g. 'https://polling.<yoururl>.octopus.app:443' ?: https://127.0.0.1:11943
```
which results in:
```
sudo /opt/octopus/tentacle/Tentacle register-with --instance "Tentacle" --server "http://127.0.0.1:8066" --name "aero2" --comms-style "TentacleActive" --server-comms-address "https://127.0.0.1:11943" --apiKey "API-XXXXXXXXXXXXXXXXXXXXXXXXXX" --space "Default" …
```
=> The linux configure-tentacle.sh script now supports setting comms ports other than 10943.

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesJobService.cs
We identified an issue where if the job took longer to run than the job TTL (default 60s), then the `jobService.Watch` call would timeout, which would "complete" the job and no longer record any logs.
This would happen most obviously the first time you acquire an execution image and the job would complete in the octopus UI before the job would execute.
Introduces a new environment variable `OCTOPUS__K8STENTACLE__JOBMONITORTIMEOUT` for adjusting the timeout of this watch call. Default's to 30min if not specified.
The watch still finishes when signalled or when the job has been deleted.
Shortcut story: [sc-70357]
=> Add new timeout for job watch api call

source/Octopus.Tentacle/Kubernetes/KubernetesJobContainerRegistry.cs
If customers are running a v1.29 Kubernetes cluster, we need to use the correct `octopuslabs/k8s-workertools` tag
https://hub.docker.com/layers/octopuslabs/k8s-workertools/1.29.1/images/sha256-977619da8d8b9f2c74392f9fca0072e7a4047b2ed6a40b26fcb05389683d77fa?context=explore
=> Add job container for Kubernetes 1.29

source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs
Related to: https://github.com/OctopusDeploy/helm-charts/pull/57
To be good Kubernetes citizens, we should set resource requests on our job containers.
Based on testing on an AKS cluster, these requests seem quite reasonable. They are fairly lightweight and barely use any memory/CPU
Shortcut story: [sc-70554]
=> Set resource requests on Kubernetes Jobs

source/Octopus.Tentacle/Kubernetes/KubernetesJobContainerRegistry.cs
For #project-k8s-agent
Now that the octopuslabs/k8s-workertools image is being published with `major.minor` tags, we can clean up this code a bit so that we get workertools images with the latest patches for a minor version.
=> Remove the patch version from job container tags

scripts/deploy/test-linux-package-from-feed.sh
In https://github.com/OctopusDeploy/OctopusTentacle/pull/231, the packaging was changed to no longer use the `linux-pacakge-feeds` docker container, and use the `tool-linux-packages` container instead.
A comment referring to the old container was left behind. 
That comment is now updated.
=> Update comment to reflect correct container

build/test-scripts/integration/common/run-integration-tests-on-vm-agents.sh
When running a command as sudo the environment and $PATH is not passed. The change here is to pass the environment as well as the path enabling the use of the scripted installed dotnet.
[SC-65861]
=> Fix dotnet mismatch in builds

build/test-scripts/integration/common/run-integration-tests-on-vm-agents.sh
We are seeing builds fail where no tests have failed e.g.:
this is probably caused because we recently changed the build script to return exit 1 when vstest has a failed test. Previously we ignored the exit code of the vstest command.
=> vstest exit code should not cause the build to fail

build/Build.Tests.cs, source/Octopus.Manager.Tentacle.Tests/ApplicationStartupSanityCheckFixture.cs, source/Octopus.Manager.Tentacle/App.xaml.cs, source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Tentacle.sln
The newly added project `Octopus.Manager.Tentacle.Tests` isn't built in TeamCity due to the project default's configuration settings. Therefore, the tests added in this project don't run in TC either.
This PR changes the project configuration settings so that `Octopus.Manager.Tentacle.Tests` will be built with `Release-net48-win` config. Additionally, a dependency section is also added to `Tentacle.sln` to ensure MSBuild builds the projects in the right order.
[sc-70950]
The test to programmatically start the WPF application caused the TC host to crash. Thus, I inverted it back to our original approach which resolves the `TentacleManagerModel`.
Tests in `Octopus.Manager.Tentacle.Tests` are run as part of the MSBuild command `TestWindows`.
Tentacle Manager tests are now run in TeamCity …
=> Fix TC build for project Octopus.Manager.Tentacle.Tests

.nuke/build.schema.json, build/Build.Pack.cs
Now that the helm chart defaults to the docker registry for tentacle, we can build locally with the tag without the artifactory repo host name.
I've updated it so that the "Push" version still pushes to artifactory, but the build and load locally option doesn't add the hostname.
=> Fix BuildAndLoadLocallyKubernetesTentacleContainerImage build target

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/Support/PendingRequestQueueFactories/CancelWhenRequestQueuedPendingRequestQueueFactory.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationTokenObservingPendingRequestQueueDecorator.cs
[SC-67117]
Bumps tentacle to using a recent version of Halibut which removes the `pollingRequestMaximumMessageProcessingTimeout`.
See  https://github.com/OctopusDeploy/Halibut/pull/595
=> Halibut no longer has PollingRequestMaximumMessageProcessingTimeout

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs
I realised while spiking out the server-driven updates that we didn't know what the namespace was for the agent but we need to know when running the helm upgrade command.
=> Add Namespace env var to k8s jobs

.nuke/build.schema.json, build-k8s-docker-local.ps1, build/Build.Pack.cs, docker/kubernetes-tentacle/dev/Dockerfile
Debugging Tentacle running in a Kubernetes cluster is challenging as you can't just hook up the debugger and go. 
To do this via Rider, we have a custom docker image that includes the Rider Remote Debugging Tools. This PR fixes the build since it was moved to `buildx` and the multi-arch images.
One key point is that this can only build a single architecture image as the rider tools are only single arch. To do this, I added a new Nuke parameter called `DockerPlatform` which allows for changing the default multi-arch platforms. Also, I added a `DockerBuilder` parameter so you can specify a custom docker build if you haven't swapped to buildx for all builds.
There is a new Nuke target to build and load the debug image. It's essentially the same, just sources a different docker file
Quality …
=> Fix building debug Kubernetes image

source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Startup/OctopusProgram.cs, source/Octopus.Tentacle/Tentacle.exe.k8s.nlog
We are correctly logging system logs to the Kubernetes pod logs, however they don't have some useful information like timestamp or log level, making it hard to correlate with other logs for timings etc.
This PR changes the target layout for the `stdout` and `stderr` targets, but only when running in Kubernetes.
=> Format kubernetes console logs with log level and timestamp

source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/SetupTentacleWizardModel.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/Views/OctopusServerConnectionTab.xaml
Customers can configure the communication port for the server and need to be able to easily configure the tentacle to use that port.
Recently the [Linux tentacle installation script was updated to support configuring a custom port](https://github.com/OctopusDeploy/OctopusTentacle/pull/792). This change exposes the same configurability in the Tentacle Manager.
The tentacle's server communication port can now be configured in Tentacle Manager.
[SC-68270]
With validation error:
- Confirm that the UI positioning makes sense
- Uses existing property for binding.
=> Allow server communication port to be overriden in Tentacle Manager

source/Octopus.Tentacle.Tests/Commands/RunAgentCommandFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitorTask.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesService.cs, source/Octopus.Tentacle/Kubernetes/OctopusLabels.cs, source/Octopus.Tentacle/Kubernetes/Scripts/KubernetesPodScriptExecutor.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesPod.cs
Superceeds #818 
In preparation for making Tentacle when running in Kubernetes a much more stateless application, we need to change how we monitor the status of jobs.
Currently, when a script is started, it spawns a `RunningKubernetesPod` which runs it's `Execute` in a background thread. In this `Execute`, it creates the pod and starts monitoring the logs & pod status. This means that if the Tentacle is torn-down or evicted etc, then we lose all that state.
This PR starts this improvement by introducing a long-running `KubernetesPodMonitorTask` which is used to watch changes to _all_ pods in the Tentacle namespace. This is then used in the `RunningKubenetesPod` to get the status. Eventually, this would be done directly in the `GetScriptStatus` RPC call, but that will come in later PR's. …
=> Monitor pod status via long-running watch task

source/Octopus.Tentacle.Tests.Integration/Support/TentacleConfigurationsAttribute.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/LinuxTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/NugetTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/TentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleVersions.cs
As more engineers are migrating to ARM based development environments, it is necessary to be able to run the Tentacle integration tests locally or on ARM based VMs. This also unlocks the capability to execute integration tests for ARM based Linux platforms.
This requires that an appropriate version of the Tentacle be downloaded as part of the tests.
Tests would fail to run on ARM platforms
Tests run on ARM platforms
- Review that the version selections are reasonable
- Quality :heavy_check_mark:
I have run these tests on Windows, Linux and Mac OS X on ARM.
=> Improve support for running integration tests on ARM 

source/Octopus.Manager.Tentacle.Tests/Octopus.Manager.Tentacle.Tests.csproj, source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj
I noticed that this project doesn't build on mac (and I presume other *nix flavours). Adding this property makes it build again. Note: this does not allow you to run the built .dll on mac or linux.
=> Add EnableWindowsTargeting to Octopus.Manager.Tentacle.Tests.csproj

source/Octopus.Manager.Tentacle.Tests/Builders/SetupTentacleWizardModelBuilder.cs, source/Octopus.Manager.Tentacle.Tests/Builders/TelemetryServiceBuilder.cs, source/Octopus.Manager.Tentacle.Tests/Utils/TentacleManagerInstanceIdentifierServiceFixture.cs, source/Octopus.Manager.Tentacle.Tests/WizardFixtures/SetupTentacleWizardFixture.cs, source/Octopus.Manager.Tentacle/App.xaml.cs, source/Octopus.Manager.Tentacle/Infrastructure/TelemetryEvent.cs, source/Octopus.Manager.Tentacle/Infrastructure/TelemetryEventBatch.cs, source/Octopus.Manager.Tentacle/Infrastructure/TentacleManagerScriptExecuted.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/ReviewAndRunScriptTabViewModel.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/SetupTentacleWizardModel.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManager/TentacleManagerView.xaml.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManagerModule.cs, source/Octopus.Manager.Tentacle/Util/TelemetryService.cs, source/Octopus.Manager.Tentacle/Util/TentacleManagerInstanceIdentifierService.cs
We currently have no visibility into our customer’s use of Tentacle Manager. This makes it difficult to decide how to prioritize potential future work, as there is no evidence on which to base these decisions.
This PR makes the first step to improve this situation by introducing telemetry to Tentacle Manager.
Tentacle Manager will now send telemetry to Amplitude (via Octopus Server) when:
_An instance of a polling Tentacle (deployment target, or worker) is installed/registered/configured._
The telemetry data is very basic and only contains:
* User ID
* Device ID (unique to the instance of Tentacle Manager)
* Communication Style (i.e. polling/listening)
* Machine Type (Worker, or Deployment Target)
Octopus Server will augment the event with some further Server-specific data before sending …
=> Add telemetry to Tentacle Manager

build/Build.Pack.cs
Currently in our Tentacle build on deploy.octopus.app, we only upload .net6.0 and net48 versions of Tentacle to AWS S3 for direct downloads.
https://deploy.octopus.app/app#/Spaces-1/projects/octopus-tentacle/deployments/releases/8.1.998/deployments/Deployments-797858
We'd like to have the .net6,0-windows version of Tentacle (which has ,NET6 Tentacle Manager bundled within) to be uploaded as well.
This PR ensures we also pack `net6.0-windows` packages when running PackCrossPlatforrmBundle, which will then later be used to upload the `msi` executable files to AWS S3.
[sc-72678]
Changes in this PR ensure we also pack `net6.0-windows` packages when running PackCrossPlatforrmBundle, which will then later be used to upload the `msi` executable files to AWS S3.
`net6.0-windows` packages were not …
=> Include net6.0-windows package when running PackCrossPlatforrmBundle

source/Octopus.Tentacle.Tests/Scripts/ExponentialBackoffFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodService.cs, source/Octopus.Tentacle/Time/ExponentialBackoff.cs
[sc-73237]
https://github.com/OctopusDeploy/OctopusTentacle/pull/824 starting using a Watcher to get updates for Pods. Unfortunately the Kubernetes API Server will [close the connection after some time](https://stackoverflow.com/questions/51399407/watch-in-k8s-golang-api-watches-and-get-events-but-after-sometime-doesnt-get-an) (we can't have the watch open forever).
This PR adds a short timeout of 10min and reloads the status after that.
We also add a try/catch around the entire status loading so we don't silently lose track of Pod statuses.
Screenshot of Pod status loading at startup:
Status is reloaded after 10min:
=> Fix bug where pod monitoring stops working after a while for Kubernetes agent

docker/kubernetes-tentacle/Dockerfile, docker/kubernetes-tentacle/dev/Dockerfile, docker/kubernetes-tentacle/dev/scripts/bootstrap.sh, docker/kubernetes-tentacle/scripts/configure-and-run.sh, docker/kubernetes-tentacle/scripts/run-tentacle.sh
Observation when updating the Kubernetes Agent tentacle container is that it always took 30s to terminate before the new container would start up. During this process, the terminating container would continue to handle halibut messages.
This indicated that Tentacle was not correctly handling the SIGTERM event that Kubernetes should be passing. Investigation indicated that because we were launching the tentacle as a sub-process of bash (which was a sub-process of the shell entrypoint), that this wasn't being passed down.
This PR updates the docker file and script
Changes the entrypoint of the kubernetes tentacle docker image to be a single bash script, which launches tentacle via `exec`, which replaces bash with the tentacle process. As a result, this becomes process with pid `1`, which is …
=> Properly propagate SIGTERM signal in Kubernetes Tentacle

docker/linux/Dockerfile, docker/linux/scripts/configure-tentacle.sh
We symlink Tentacle into /usr/local/bin in the configure tentacle script, which runs at container start. For users running the container in a `readonlyrootfilesystem` security context, this means that they need to use a volume mount or other convoluted setup for this one file. Baking it into the docker build step, removes this need.
=> Move symlink generation into dockerfile

source/Octopus.Tentacle.Tests/Commands/RunAgentCommandFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesOrphanedPodCleanerTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle/Background/BackgroundTask.cs, source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleaner.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleanerTask.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitorTask.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodService.cs, source/Octopus.Tentacle/Maintenance/WorkspaceCleanerTask.cs
[sc-73516]
Sometimes a script pod gets orphaned, where for what ever reason server doesn't care about it anymore so it gets left in a completed or failed state, but it never gets cleaned up.
I've created a new task which creates a new task which checks for orphaned pods every 10 minutes. A pod is considered orphaned if it's in a non-running state, and has not received an update within 10 minutes.
When `OCTOPUS__K8STENTACLE__DISABLEAUTOPODCLEANUP` is `true`, orphaned pods are not deleted, but we log a verbose message saying we are not deleting the pod.
=> Automatic Cleanup of Orphaned Pods

docker/kubernetes-tentacle/bootstrapRunner/bootstrapRunner.go
We should be doubly sure that we've written all logs from the buffer before exiting
Added flush calls to both bufio writers
=> Force flush to log files before bootstrapRunner exits

source/Octopus.Tentacle.CommonTestUtils/Builders/StartScriptCommandBuilder.cs, source/Octopus.Tentacle.CommonTestUtils/Builders/StartScriptCommandV2Builder.cs, source/Octopus.Tentacle.CommonTestUtils/Builders/StartScriptCommandV2BuilderExtensionMethods.cs, source/Octopus.Tentacle.CommonTestUtils/Builders/StartScriptCommandV3AlphaBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/ScriptExecutionOrchestrator.cs
As part of the feedback for #845 from @LukeButters, he recommended certain changes be a separate PR, so here it is 😄 
This PR moves the start script command builders into the `CommonTestUtils` project. These builders are only used in the tests as well as in Server, however with the follow up PR #845 and https://github.com/OctopusDeploy/OctopusDeploy/pull/23506, these are no longer to be used in Server.
These were move into the contracts library in Jan by @nathanwoctopusdeploy  in #764 so they could be used in DynamicWorkers, in the upcoming PR they aren't used in TentacleClient, so they don't need to be in the contracts library
I also change 2 default values for the `StartScriptCommandV3Alpha` to be consistent with the `LatestStartScriptCommandBuilder`
=> Move start script command builders to test utils

source/Octopus.Tentacle/Commands/RunAgentCommand.cs, source/Octopus.Tentacle/Configuration/Crypto/LinuxGeneratedMachineKey.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceManager.cs, source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceSelector.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Services/ServicesModule.cs, source/Octopus.Tentacle/Startup/OctopusProgram.cs, source/Octopus.Tentacle/Util/OctopusPhysicalFileSystem.cs, source/Octopus.Tentacle/Util/PlatformDetection.cs
This PR splits out a few changes from #852 to make it easier to review that PR and understand the changes.
To make it clearer about when the Tentacle code is running as the Kubernetes agent, I have changed the `PlatformDetection.Kubernetes.IsRunningInKubernetes` check to be `IsRunningAsKubernetesAgent` and changed the environment variable to be one that is always set when running as the Kubernetes agent.
I also removed the `KubernetesConfig.ExecuteScriptsInLocalShell` because we are never going to execute scripts in a local shell when running in the Kubernetes agent.
Shortcut story: [sc-73757]
=> Rename IsRunningInKubernetes to IsRunningAsKubernetesAgent

source/Octopus.Tentacle.Tests/Communications/AutofacServiceFactoryFixture.cs, source/Octopus.Tentacle/Communications/AutofacServiceFactory.cs, source/Octopus.Tentacle/Services/ServicesModule.cs
Halibut services were being registered in a nested scope of the main lifetime scope. This caused an issue in #860 where they then couldn't be resolved in another part of the application due to the incorrect scoping.
This PR changes Halibut services to be registered in the root lifetime scope, however still maintains the nested scope for _each_ execution of an RPC call.
Because all halibut services are registered as `SingleInstance`, it means they are shared to all nested scopes. If there are services that will need to be per RPC call, we create a nested scope for each call to `CreateService`, which returns a `IServiceLease` that lives for the lifetime of the RPC call in halibut and is disposed at the end.
Ideally, each service wouldn't be registered as `SingleInstance` but Tentacle …
=> Change the Autofac scope Halibut services are registered in

.github/CODEOWNERS
Adding Modern Deployments as owners of the Kubernetes code in Tentacle
=> Add Modern Deployments as owners of Kubernetes code

source/Octopus.Tentacle/Communications/AutofacServiceFactory.cs, source/Octopus.Tentacle/Communications/IServiceRegistration.cs, source/Octopus.Tentacle/Maintenance/IRunningScriptReporter.cs, source/Octopus.Tentacle/Maintenance/WorkspaceCleaner.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV3Alpha.cs
Workspace cleaner is resolving the script services by name via a service locator-style pattern, which is generally considered an [anti-pattern](https://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/).
This will also cause an issue in a forthcoming PR as the `KubernetesScriptServiceV1Alpha` will not be registered for normal tentacles, so we need a way to not resolve the services directly.
This PR introduces a new interface, `IRunningScriptReporter` which is added to the appropriate script services and exposes a single `IsRunningScript(ScriptTicket)` method.
Then the workspace cleaner receives a list of registered `IRunningScriptReporter`'s, which it then can do an `Any()` on to see if any of the services are running that script ticket.
To support this change, halibut services are …
=> Change the WorkspaceCleaner to load script services by new interface

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesOrphanedPodCleanerTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleaner.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs
Rather than creating our own date time, we can use the Finished At property on the Pod we get from the API.
=> Update orphaned pod cleaner to use the "FinishedAt" property on the Pod

source/Octopus.Tentacle.Contracts/Services/Scripts/IAsyncScriptServiceV2.cs
@LukeButters This is the interface we needed in my test PR.
Should we always have exposed this interface like this?
Similar to https://github.com/OctopusDeploy/OctopusTentacle/pull/853
=> Expose IAsyncScriptServiceV2, maintaining location of service

docker/linux/Dockerfile, docker/linux/scripts/configure-and-run.sh, docker/linux/scripts/configure-tentacle.sh, docker/linux/scripts/run-tentacle.sh
When a container is shut down (e.g., via `docker stop`), the root process is sent the `SIGTERM` signal and given a grace period to shut down before being sent `SIGKILL`. Tentacle has support for handling this event, but due to script nesting, the signal is not propagated to the Tentacle process.
Including Docker-In-Docker introduces additional complexity, as both processes need to receive the signal. The container should also coordinate the independent failure of either process and signal the other to terminate.
- Graceful shutdown will occur when stopping a Tentacle container.
- If the Docker in Docker daemon terminates (e.g. crashes), the Tentacle will be terminated gracefully.
- Shortcut [SC-73505]
- Resolves #865 
To test the PR, I created a small application that would run in the …
=> Trap SIGTERM and send to tentacle

.nuke/build.schema.json, build/Build.Pack.cs
If using Microk8s to build, the registry we want to push to exists on a different IP address, so this PR just gives an easy wrapper to build and push a container image to this registry.
If you'd like, feel free to spool up microk8s and the registry and attempt to use the step, though I've already run and tested locally :)
=> Add build step for pushing microk8s image

source/Octopus.Manager.Tentacle.Tests/ConfiguringTentacleServiceFixture.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/InstanceConfigurationLoader.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManager/TentacleManagerModel.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManagerModule.cs
We've had a bug turn up in Tentacle Manager [sc-74641], which occurs in the specific scenario where:
1. There are multiple instances of Tentacle installed, _and_
2. There is no default instance i.e. an instance named **(Default)**
This bug manifests as a nasty looking error in the UI which also prevents the user from being able to configure the Tentacle(s):
The bug is caused by some [changes to the configuration code in Tentacle itself](https://github.com/OctopusDeploy/OctopusTentacle/pull/674). Tentacle Manager uses these same classes to load configuration and display to the user, but Tentacle and Tentacle Manager do not operate in the same way and these changes are not compatible with Tentacle Manager.
The fix in this PR does the following:
1. Moves the configuration loading logic from …
=> Remove usage of ApplicationInstanceSelector from Tentacle Manager

docker/kubernetes-tentacle/bootstrapRunner/bootstrapRunner.go, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/PodLogLineParserFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/TrackedScriptPodFixture.cs, source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/PodLogLineParser.cs, source/Octopus.Tentacle/Kubernetes/PodLogReader.cs
[sc-71685]
Once a Pod has completed running its script, the Kubernetes API Server can take a few seconds to reflect the status update.
This PR adds an End-of-Stream (EOS) message to the bootstrapper script so we can detect this quicker than the Kubernetes API.
For a deployment process with 7 steps:
- No EOS: **1m50s**
- With EOS: **1m43s**
=> Add End-of-Stream (EOS) Marker to speed up Script Pod completion

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesOrphanedPodCleanerTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/PodLogReaderFixture.cs, source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/InMemoryTentacleScriptLog.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleaner.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/PodLogReader.cs, source/Octopus.Tentacle/Kubernetes/TentacleScriptLogProvider.cs, source/Octopus.Tentacle/Services/Scripts/Kubernetes/KubernetesScriptServiceV1Alpha.cs
[sc-71685]
Now that we pull Script Pod logs directly from the K8s API, we need another way for Tentacle to add messages to the task log (previously this was all on the file system).
This PR adds an in-memory log that gets merged with the Script Pod logs. There's a catch that you'll lose the in-memory log messages if Tentacle is restarted (but these are verbose debugging messages, so they shouldn't affect deployment)
=> Add ability for Tentacle to write to the task log

source/Octopus.Tentacle/Communications/HalibutInitializer.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
Now we have [safeguards](https://github.com/OctopusDeploy/Halibut/pull/599) in Halibut to stop DoS-ing a server, we can add a new environment value to open multiple polling connections. This improves throughput and performance by having multiple connections polling for work.
The env var name is `TentaclePollingConnectionCount`.
I also considered adding a hard max per tentacle (say 16 or something), but felt like people setting this env var should understand what that means to the target server. As mentioned, we also have the new safety nets in Octopus Server to handle this.
Will be tested via the k8s agent against a branch instance with the Server limit set
Shortcut story: [sc-74991]
=> Support opening multiple polling connections

source/Octopus.Tentacle/Communications/HalibutInitializer.cs
Small mistake from #881 . NO functionality change, but now we only change the constant to change the max
=> Use the defined max connections constant

docker/kubernetes-tentacle/bootstrapRunner/bootstrapRunner.go, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesOrphanedPodCleanerTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/PodLogLineParserFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/PodLogReaderFixture.cs, source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesClientExtensionMethods.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleaner.cs, source/Octopus.Tentacle/Kubernetes/PodLogLineParser.cs, source/Octopus.Tentacle/Kubernetes/PodLogReader.cs, source/Octopus.Tentacle/Kubernetes/ScriptPodSinceTimeStore.cs, source/Octopus.Tentacle/Services/Scripts/Kubernetes/KubernetesScriptServiceV1Alpha.cs
[sc-71685]
We currently stream all logs from the Script Pod every time. There's a `sinceTime` filter we can use to only get the latest logs.
This PR adds `sinceTime` to the request we send. We also depend on the API Server's timestamp now instead of writing our own in the bootstrapper - in case the clocks are out of sync.
=> Only pull Script Pod logs newer than the last set we got

source/Octopus.Tentacle.Tests/Kubernetes/PodLogReaderFixture.cs, source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/PodLogReader.cs
[sc-71685]
This PR builds on top of https://github.com/OctopusDeploy/OctopusTentacle/pull/879/files#r1556936695 to ensure we error if the Script Pod logs look out of shape.
=> Assert all Script Pod logs are in sequential order

.nuke/build.schema.json, source/Octopus.Tentacle.Client/Scripts/Models/Builders/ExecuteKubernetesScriptCommandBuilder.cs, source/Octopus.Tentacle.Client/Scripts/Models/ExecuteKubernetesScriptCommand.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV3AlphaOrchestrator.cs, source/Octopus.Tentacle.CommonTestUtils/Builders/StartKubernetesScriptCommandV1AlphaBuilder.cs, source/Octopus.Tentacle.Contracts/KubernetesScriptServiceV1Alpha/StartKubernetesScriptCommandV1Alpha.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
The Kubernetes Agent will soon have functionality to allow Octopus Server to specify a pre-configured Kubernetes service account that the pod that the individual script is run inside of.
Adds a new `ScriptPodServiceAccountName` property to the `ExecuteKubernetesScriptCommand` which is then included in the `StartKubernetesScriptCommandV1Alpha` as a nullable/optional property. Providing no value (`null`) results in the existing behaviour of using the service account created as part of the helm chart. Any non-whitespace string provided here is used in lieu of this when create the pod.
No validation is performed on the supplied service account name.
Shortcut story: [sc-75593]
=> Add ability to set Kubernetes script pod service account

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Util/ListExtensions.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
When NFS goes down, we can get corrupted file shares, which are impossible to read from, but can be written to (but not persisted over the network). This causes all sorts of issues, so we've decided that deleting the pod (which also deletes the mount) is the safest way to recover from this error, so that we don't expect that we've completed work which hasn't persisted. 
This led to the creation of the Kubernetes Agent NFS Watchdog, which checks that there are no read errors coming from the agent. It's designed to run as a lightweight sidecar, and will delete the pod it's running in if there are read errors.
This PR adds the NFS watchdog to all script containers spawned by the tentacle agent. 
If NFS _or_ the watchdog itself is not in use, the environment variables that we use to determine …
=> Add NFS watchdog to script pods

source/Octopus.Tentacle/Octopus.Tentacle.csproj
Updating the [Kubernetes SDK](https://github.com/kubernetes-client/csharp) to `13.0.26` means we support clusters running `1.29`, `1.28` & `1.27`
It's very likely that this does support older versions and be forwards compatible as well as we are using API endpoints that have existed for a long time.
=> Update Kubernetes SDK to 13.0.26

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesVersionParserTests.cs, source/Octopus.Tentacle/Kubernetes/KubernetesClusterService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesVersionParser.cs
EKS returns the cluster version as, where the minor version number has a non-numeric character which causes the cluster version parsing to fail with a `System.FormatException`
```
{
"major": "1",
"minor": "29+",
"gitVersion": "v1.29.1-eks-b9c9ed7",
"gitCommit": "07600c74de018baffb16c82771a48adcb843a932",
"gitTreeState": "clean",
"buildDate": "2024-03-02T03:46:35Z",
"goVersion": "go1.21.6",
"compiler": "gc",
"platform": "linux/amd64"
}
```
[SC-75848]
- Added `KubernetesVersionParser` class to handle the parsing of version numbers related to K8s and refactored `KubernetesClusterService` to use it.
- Moved `ClusterVersion` into `KubernetesVersionParser`
- Added tests for `KubernetesVersionParser` 
=> Sanitize Kubernetes cluster version

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/TrackedScriptPodFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Services/Scripts/Kubernetes/KubernetesScriptServiceV1Alpha.cs
[sc-74374]
We want to know if a Pod can't be scheduled due to cluster problems - this PR logs a verbose message for the Pod state for every `GetStatus` request.
We still get 3 `Pending` log messages when the Pod gets scheduled immediately, hence the verbose level.
=> Show Script Pod phase to help users troubleshoot

source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs
[sc-71685]
When reading Pod logs, we may occasionally hit a transient error that should be retried.
This PR adds up to 5 retries with exponential backoff.
=> Add retries to Pod log reading

source/.run/Build and Push Kubernetes Tentacle docker image (powershell, amd64).run.xml, source/.run/Build and Push Kubernetes Tentacle docker image (shell, arm64).run.xml, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesAgentIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesClusterOneTimeSetUp.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesTestsGlobalContext.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/DockerImageLoader.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesAgentInstaller.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesClusterInstaller.cs
When developing the Kubernetes Tentacle/Agent locally, it will help developers if they can run the integration tests against locally built images.
This change adds this ability by inspecting the local docker image cache and then using `kind load docker-image` to load it into the integration test cluster.
On TeamCity, we still use the built image as pushed to Artifactory
Developers will need to run the `BuildAndLoadLocallyKubernetesTentacleContainerImage` Nuke build target first, before executing the tests. I played with running this during the test itself, but it didn't work due to dll locking and other things.
I've added 2 new rider build configurations to execute this nuke configuration.
=> Use locally built docker image in Kubernetes integration tests

installer/Octopus.Tentacle.Installer/Product.wxs, source/Octopus.Tentacle/Configuration/LogInitializer.cs
[SC-73181]
When the logging directory configuration is changed the change isn't picked up by NLog immediately and there is a quite a significant delay until it actually does, this is potentially okay for long running commands since it will eventually start logging in the correct location but for anything else it means that the logs will always end up in the default directory `Octopus/Logs` rather than the `{TentacleHome}/Logs`. This only seems to be an issue for the K8s agent, the standard polling/listening tentacles aren't affected.
- Updated `LogInitializer` to update the NLog configuration with a reloaded version of it which has the updated logging directory 
*Note*: The log line that is just `Changed log folder from Octopus/Logs to /octopus/Logs` is meant to appear …
=> Force configuration to reload after changing the logging directory

source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs
If there are multiple containers in a script pod, we would wait for all containers to exit cleanly. This may not always be the case. For example, the NFS watchdog runs as a sidecar, and if the cluster has a service mesh with sidecar injection, the same issue would arise.
Fixes [sc-76109]
Now, when we check the pod's status, we check the container status of the script pod to determine whether the job completed successfully or not. We check this container status if the pod is in `Running`, `Failed`, or `Successful`, as the container itself may be successfully completed in any of these situations. 
I considered making integration tests for this, but wanted to get the fix in first.
I've completed smoke testing, but it may be worth completing some more on a live …
=> Use container status, not pod status to determine phase

source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1AlphaIntegrationTest.cs, source/Octopus.Tentacle/Kubernetes/IKubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesService.cs
[sc-76250]
During test, we found that sometimes the Pod logs returned by the K8s API was missing the first 3 lines, but the lines were there on a retry.
This problem is difficult to reproduce, so we've decided to add a simple retry to cater for the case where the K8s API isn't returning the Pod log lines we're expecting.
=> Retry when Pod log line numbers don't match

source/Octopus.Tentacle/Kubernetes/KubernetesPodContainerRegistry.cs
[SC-76030]
The image used in the ScriptPod is currently been pulled from Artifactory a PR in the image repo  https://github.com/OctopusDeploy/kubernetes-agent-tools-base/pull/5 is going to make it push the image to dockerhub.
Updated to get the image from dockerhub
=> Update ScriptPod to pull image from Dockerhub

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesDirectoryInformationProviderFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPhysicalFileSystemFixture.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesUtilitiesFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesDirectoryInformationProvider.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPhysicalFileSystem.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesUtilities.cs, source/Octopus.Tentacle/Util/OctopusFileSystemModule.cs, source/Octopus.Tentacle/Util/OctopusPhysicalFileSystem.cs, source/Octopus.Tentacle/Util/ShellModule.cs, source/Octopus.Tentacle/Util/SilentProcessRunner.cs
**Note that this change will require a [new helm chart version](https://github.com/OctopusDeploy/helm-charts/pull/125) to get a required environment variable!** 
When running Octopus Tentacle in the Kubernetes Agent, we can't reliably get disk space on the mounted volume using native disk space tools. This is because in some cases (especially using the default NFS implementation), the volume is actually an NFS export of a folder on the node. This means that disk space tools (like `df`) show the disk space free on the _node_ rather than the disk space that we've configured in Kubernetes to be available. When we exceed the disk space we've configured in Kubernetes, `kubelet` will evict the NFS pod.
As such, we've fallen back to using a simple `du` command to quickly get the disk space used …
=> Use `du` for space checks in Kubernetes

source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesAgentInstaller.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/agent-values.yaml
Now we have published `1.0.0` of the Kubernetes Agent helm command, we need to update the helm chart values in the integration tests.
I also added the ability to specify a custom helm chart version via `KubernetesIntegrationTests_HelmChartVersion` environment variable which will try and pull that version from Artifactory. This is useful when the Tentacle changes being tested need a custom build of the helm chart (such as new env vars)
=> Update integration test Helm command

source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
If a user has any nodes that are running linux with a 32 bit or other architecture, this change will make sure that kubernetes doesn't try to schedule script pods on those nodes as we only have container images for linux/amd64 and linux/arm64.
A related change is being made in the helm chart repo so that kubernetes won't schedule nfs or tentacle pods on nodes with invalid architectures: https://github.com/OctopusDeploy/helm-charts/pull/136
=> Using node affinity to also specify that script pods must use arm64 or amd64 nodes

source/Octopus.Tentacle.CommonTestUtils/Diagnostics/InMemoryLog.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesDirectoryInformationProviderFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesDirectoryInformationProvider.cs
[sc-77040]
When DU fails to get the disk usage, it'd be good to get the reasons for failure, which usually come in `stdout`. Improperly printing a list led to this not being done in production. This change ensures that the logs are available in the Tentacle container, and adds a test to make sure it continues to work.
The logs from DU now show correctly as comma-delimited output in the console logs.
=> Fix logging when DU fails

source/Octopus.Tentacle/Scripts/IScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspaceFactory.cs
When cleaning up workspaces, Tentacle checks for available free space. This check is not necessary during this process.
Move the check out of the constructor so that a `ScriptWorkspace` can be created without performing the check. The check can now be performed by calling the `CheckReadiness()` method on `IScriptWorkspace`. This helps separate the side effect from the object creation.
All creation of script workspaces is managed through the `ScriptWorkspaceFactory` which will perform this check when getting a Workspace.
For uncompleted workspaces, the check does not need to be performed.
Fixes #920 
- Quality :heavy_check_mark:
- Method naming feedback/alternative suggestions
=> Move free space check out of Workspace constructor

docker/kubernetes-tentacle/Dockerfile
[sc-77472]
When running the Kubernetes agent on OpenShift, Tentacle would fail to start due to permission errors.
This PR uses [this documentation](https://docs.openshift.com/container-platform/4.15/openshift_images/create-images.html#use-uid_create-images) to add support.
=> Add openshift random user support

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesDirectoryInformationProviderFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesDirectoryInformationProvider.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
When we run `du`, it takes a lot longer to get information back instead of using the normal disk APIs. This can slow down scripts quite a lot when running in parallel. The disk space is unlikely to change much in a short period of time so we plan to cache the results to speed things up a bit. 
[There is an ADR for this change.
](https://github.com/OctopusDeploy/adr/pull/10)
This PR adds an IMemoryCache that caches for 30s, as well as tests to ensure the cache behaviour is correct. In practice, we've seen the following results:
_For 50 Concurrent Cloud deployments_
| Cache Length | Time per Deployment |
| ------------ | ------------------- |
| No DU        | 8min                |
| No Cache     | 30min               |
| 60s          | 9min                |
| 30s          | 11min …
=> Add simple cache to directory information provider

source/Octopus.Tentacle.Tests/Commands/RegisterMachineCommandFixture.cs, source/Octopus.Tentacle/Commands/RegisterMachineCommand.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
When registering a machine, we only accept environment names. This is a problem as the Kubernetes agent helm chart is generated with the environment slugs. This PR updates `Octopus.Client` to get the changes in https://github.com/OctopusDeploy/OctopusClients/pull/845, which allow for environment names, slugs or Ids.
The change in OctopusClients is backwards compatible, so if you provide only environment names, it continues to work.
Uses the new property `IRegisterMachineOperation.Environments` instead of `EnvironmentNames` and adjusted the command line message to say you can use slugs, ids and names.
Tested locally using Kubernetes agent registration where there is a mix of slug, id and name
`--set agent.targetEnvironments="{qa,Environments-42,development}" `
results in 
Where env …
=> Support registering machines with environment slug or ids

source/Octopus.Tentacle.Client/Scripts/Models/Builders/ExecuteScriptCommandBuilder.cs, source/Octopus.Tentacle.Client/Scripts/Models/Builders/ExecuteShellScriptCommandBuilder.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1AlphaIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionAdditionalScripts.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptArgumentsWork.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptFilesAreSent.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV2IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/TestExecuteScriptCommandBuilderExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/TestExecuteShellScriptCommandBuilder.cs
I had some feedback from @sburmanoctopus that the ExecuteScriptCommandBuilder method names don't match our standards. I renamed the methods and will update Server with these changes in a following PR
=> Rename ExecuteScriptCommandBuilder methods

source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesAgentInstaller.cs
[sc-78146]
Currently we're only trying up to 2.5s for the Agent to generate a thumbprint and put it into the config map. This time may not be enough depending on how fast the Teamcity agent is running.
Sample failing test:
https://build.octopushq.com/test/3616094188807382982?currentProjectId=TeamFireAndMotion_OctopusTentacle_VLatest&expandTestHistoryChartSection=true
This PR simply extends the time we wait from 2.5s to 10s. @tleed5 is in the [process of changing the Helm chart such that we provide the thumbprint to the Agent](https://octopusdeploy.slack.com/archives/C05KK1G85J5/p1715129850265649?thread_ts=1715124896.774339&cid=C05KK1G85J5) (rather than try to retrieve it later) - so this code will go away soon.
=> Fix Kubernetes Agent integration test flake

source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs
[sc-78418]
The test `WhenRunningTentacleAsAServiceItShouldBeAbleToRestartItself ` has been flaky for a while, and needs to be made stable.
It is currently permanently muted for Linux builds, but it still fails on Windows sometimes. This PR addresses one of the causes for the Windows failure.
For most of the failures found ([for example](https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacle_VLatest_IntegrationTestNet60onWindows10ltscNet48service/12062342?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandPull+Request+Details=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)), the logs would show `The Tentacle failed to start correctly`:
It would then show the …
=> Helping Fix one cause of the flaky WhenRunningTentacleAsAServiceItShouldBeAbleToRestartItself Test

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs
[sc-70984]
The `ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.DuringStartScript_ForListeningTentacle_ThatIsRetryingTheRpc_AndConnecting_ScriptExecutionCanBeCancelled` test was flaky. 
On closer inspection, it was found that when it failed, it was forever trying to send a `Cancel` message to the Tentacle when it should not be.
It looks as though what was happening was that an exception was being thrown during "prepare exchange" in Halibut, and this exception was being considered as `ConnectionState.Unknown`. 
The reason we care about the connection state is because if we cancel, and encounter an exception while connecting, then we can walk away. The Tentacle never received any instructions.
But if we encounter an exception after we have connected, then the Tentacle may have …
=> Fixing DuringStartScript_ForListeningTentacle_ThatIsRetryingTheRpc_AndConnecting_ScriptExecutionCanBeCancelled 

source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/HalibutTimeoutsAndLimitsForTestBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationObservingPendingRequestQueueFactory.cs
so test client halibut settings can be configured from a single place.
Also updates the client halibut to use tcp keepalive, since that is default in places that use the tentacle client.
=> Adds a HalibutTimeoutsAndLimitsForTestBuilder

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/Support/HalibutTimeoutsAndLimitsForTestBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
Background: https://brooker.co.za/blog/2024/05/09/nagle.html
TLDR; TCP_NODELAY=true results in much faster for RPC performance in linux. TCP_NODELAY disables a TCP setting that makes sense when humans type characters into telnet (buffer the chars before sending because humans are slow) but less sense in halibut since when we send a thing we actually would like it to go over the wire now.
This PR adds an option to use: https://github.com/OctopusDeploy/Halibut/pull/610
Additionally TCP_NODELAY is used by default in tests.
[SC-76274]
=> Add option to use tcp_nodelay in tentacle, also use the option in integration tests.

docker/kubernetes-tentacle/dev/Dockerfile
The dev Dockerfile is used to build the image of tentacle for remote debugging. This has not been kept up to date as it is missing the bootstrap runner executable.
The PR brings the debug tentacle image up to date with the prod one (at least in terms of the bootstrap runner part).
=> Add bootstrap runner exe to the debug tentacle image

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPhysicalFileSystem.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Util/OctopusFileSystemModule.cs
The Kubernetes Script Pods use a PV mount to get access to the shared file system managed by the Kubernetes Tentacle. When Calamari is acquiring packages, it checks if it should do package cleanup first.
Currently the Calamari implementation cannot do package retention when in the Kubernetes agent because it is not able to calculate the amount of storage on the PV.
[sc-76306]
This PR gets the Kubernetes Tentacle to add PV storage information (total bytes and free bytes) to the environment variables passed to Script Pods.
There is a Calamari PR () to utilise these variables to correctly calculate if package retention needs to be executed.
=> Pass PV storage information to script pods as Environment Variables for Calamari package retention

docker/kubernetes-tentacle/scripts/configure-and-run.sh
We need to allow users to specify multiple server comms addresses to support Octopus Server running in an HA configuration.
[sc-75000]
Fortunately, there is already a command in Tentacle that we can leverage to register extra server instances (`poll-server`) so I just added an extra variable which can have multiple values, one for each additional server to register.
To make things backwards compatible, I've kept the original variable and now support both in the following way:
If `ServerCommsAddress` (singular) is set, it will use that for the initial registration. In this case, if `ServerCommsAddresses` (plural) is also set, all those values will be registered via `poll-server`.
If `ServerCommsAddress` is **not** set, the first value of `ServerCommsAddresses` will be used instead, and the …
=> Allow users to specify multiple Server Comms Addresses to support HA Server configurations

docker/kubernetes-tentacle/scripts/configure-and-run.sh, source/Octopus.Tentacle.Tests/Commands/StubTentacleConfiguration.cs, source/Octopus.Tentacle/Commands/ClearTrustedServersCommand.cs, source/Octopus.Tentacle/Commands/OptionSets/ApiEndpointOptions.cs, source/Octopus.Tentacle/Commands/PollCommand.cs, source/Octopus.Tentacle/Configuration/ITentacleConfiguration.cs, source/Octopus.Tentacle/Configuration/TentacleConfiguration.cs, source/Octopus.Tentacle/Program.cs
Recently we added the ability to define multiple `ServerCommsAddresses` to the Kubernetes Tentacle so that it could be configured to run with an Octopus Server HA Cluster setup.
The missing functionality was allowing users to adjust this configuration after installation.
With these changes, it's possible to adjust the configuration by doing a helm update:
```bash
helm upgrade --atomic \
--set agent.serverCommsAddresses="{http://host.docker.internal:10943/,http://host.docker.internal:10942/}" \
--reuse-values \
--create-namespace --namespace octopus-agent-scme \
scme \
/Users/scottmerchant/Documents/dev/helm-charts/charts/kubernetes-agent
```
[sc-75000]
=> Adjust Kubernetes Tentacle startup to always refresh server comms address registration

source/Octopus.Tentacle.CommonTestUtils/Builders/ScriptBuilder.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesAgentIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesClusterOneTimeSetUp.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1AlphaIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1IntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesAgentInstaller.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Tooling/KubeCtlTool.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Util/ExecuteKubernetesScriptCommandBuilderExtensionMethods.cs
We need some more test overage for the `KubernetesScriptServiceV1` and it's interactions with `TentacleClient`. This PR does that 😄 
Adds 4 more tests:
- `TentaclePodIsTerminatedDuringScriptExecution_ShouldRestartAndPickUpPodStatus` which tests that when the tentacle pod is terminated, that the script continues running and that a new tentacle pod is created and continues reading the logs
- `WhenALongRunningScriptIsCancelled_TheScriptShouldStop` which tests that cancellation
- `SimpleScriptExitsWithErrorCode_ScriptFails`  which tests that when a script explicitly exits with an error code, that it is reflected
- `ScriptPodIsTerminatedDuringScriptExecution_ScriptFails` which tests when the script pod deleted that the script exits with an error
=> Add some more integration tests for Kubernetes Agent

docker/kubernetes-tentacle/scripts/configure-and-run.sh
Currently you can run the helm upgrade command for a Kubernetes agent and it will install and helm will be happy even if there is no server running to connect to.
When the tentacle starts up, Kubernetes sees the container running and helm just thinks it's good to go, even though the configuration/initialisation hasn't completed yet. This can put the agent in a situation where the Tentacle container is constantly bootlooping, unable to do anything while the helm chart returned happy.
This change is coupled with another change in the helm-chart (https://github.com/OctopusDeploy/helm-charts/pull/167) to add a startup probe. This change simply adds an empty file to the `/scripts/` folder to indicate that the initialisation is complete. The startup probe checks if the file exists, as soon as …
=> Add file to indicate when tentacle is initialised

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
As part of adding Kubernetes Agent support for HA clusters, we want to allow health checks to check if the agent is configured correctly with the right number of ServerCommsAddresses.
[sc-80605]
This partners with a Server change which will compare the number of nodes to the number of configured ServerCommsAddresses and fail if the number is not the same. For backwards compatibility, if the value isn't set, it will be ignored on Server.
Related server change: https://github.com/OctopusDeploy/OctopusDeploy/pull/25129
Related documentation change: https://github.com/OctopusDeploy/docs/pull/2323
=> Add ServerCommsAddresses as env var to script pods

source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesAgentInstaller.cs
We've been hitting rate limiting because docker is tightening up their rate limits.
Instead of doing what we do in server which is to return inconclusive when dockerhub rate limits our request, we are just going to use Artifactory. This will eliminate the rate limiting but could cause failures if artifactory is down. Because this test doesn't have to run on the same scale as server, we don't need to stress too much about this. If it does fail, we can just rerun the test.
=> Use Artifactory instead of dockerhub to source helm chart

source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1IntegrationTest.cs
The exit code changes and I'm not sure why. Changing the test to verify that it's just a non-success error code
=> Fix flaky Kubernetes integration test

source/Octopus.Tentacle.Client/Scripts/KubernetesScriptServiceV1Orchestrator.cs, source/Octopus.Tentacle.Client/Scripts/Models/Builders/ExecuteKubernetesScriptCommandBuilder.cs, source/Octopus.Tentacle.Client/Scripts/Models/ExecuteKubernetesScriptCommand.cs, source/Octopus.Tentacle.Contracts/KubernetesScriptServiceV1/StartKubernetesScriptCommandV1.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1IntegrationTest.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesRawScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Octopus.Tentacle/Services/Scripts/Kubernetes/KubernetesScriptServiceV1.cs
There is a known issue with Server running the upgrade script on the Kubernetes agent where if the helm chart has changed in such a way that an NFS Pod restart is required, the script pod doing the upgrade will be forcefully killed by the nfs watchdog. This is reported to server as a failure so the upgrade fails and there is no follow up health check to get the latest version details. The upgrade itself might actually succeed, but because the task fails in server, it requires the user to do a health check before they can use it.
~To just fix the issue above, we could just disable the NFS watchdog for scripts that don't need it (raw scripts with no dependencies). However thinking about this holistically, I thought it might be even better to remove the volume mount requirement all together …
=> Kubernetes agent - Allow basic raw scripts with no dependencies to run without a volume mount

docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh
To support customers with custom certificates, a new helm-chart PR has been created
https://github.com/OctopusDeploy/helm-charts/pull/188
Debian requires that the certificate be hashed (which creates a symlink to the original file, but with a hashed filename) to be used.
Rather than stuff around with init-containers or lifecycle events, we are including this rehash at the start of the `configure-and-run.sh` script as it's fast and safe.
=> Call openssl rehash in Kubernetes agent startup script

source/Octopus.Tentacle/Kubernetes/KubernetesPodContainerRegistry.cs
We published the `1.30` tag for the `kubernetes-agent-tools-base` image, but forgot to update the known tags in the resolver. In practice it doesn't really matter because running on a 1.30 cluster, it defaults to `latest`, which is the `1.30` tag anyway, but still :)
=> Add the 1.30 tag to the known Script pod container tags

docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh
When diagnosing issues with a customers agent installation, their logs indicated that the `mkdir` call was failing 
`mkdir: cannot create directory '/etc/octopus': File exists`
Adding the `-p` flag suppresses the error if the directory already exists. I'm not 100% _why_ the directory already exists. My initial suspicion is maybe something to do with Logs being written during registration and creating that directory before the `markAsInitialised` is called
=> Don't fail mkdir if directory already exists

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
A customer reported that they would like to be able to add an `imagePullSecret` to the script pods as their nodes are dynamically created, so the image is being pulled regularily and they are running into the docker hub rate limiting.
This PR adds a new environment variable `OCTOPUS__K8STENTACLE__PODIMAGEPULLSECRETNAMES` which is a comma separated list of secret names to be used in the `imagePullSecrets` for the script pods.
Related Helm PR: https://github.com/OctopusDeploy/helm-charts/pull/214
=> Add support for imagePullSecrets to be supplied to script pod

build/Build.Pack.cs, build/Build.Tests.cs
Dockerhub is no longer providing rate-limit exemptions for Azure-hosted services. ([slack thread ref](https://octopusdeploy.slack.com/archives/CDANN5QLT/p1719890200247119)) This leads to failures on the **Test: Linux Packages**.
The [team discussed](https://octopusdeploy.slack.com/archives/C01HH8T16G3/p1719897407362199?thread_ts=1719894614.969379&cid=C01HH8T16G3) and to unblock the build pipeline, we will use Octopus artifactory as a proxy for the docker images needed by the build.
=> pull docker image from artifactory

source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/agent-values.yaml
Similar to the change made in #973, the kubernetes integration tests are intermittently failing due to docker rate limits.
After discussing with the builds team, they let us know that artifactory will proxy and cache the container pull to docker hub if the container is not in artifactory.
Updated the agent values file to change all the default container image repositories to be artifactory.
- [ x] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
=> Update k8s agent tests to pull from Artifactory

docker/kubernetes-agent-tentacle/Dockerfile, docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh
We had a customer ask if we supported the polling proxies in the Kubernetes agent. We didn't, however tentacle does support this via the `polling-proxy`  command. This PR adds support for this in the `configure-and-run.sh` script via environment variables supplied by the helm chart.
Adds a new method to the `configure-and-run.sh` that calls the `polling-proxy` command.
Shortcut story: [sc-83658]
=> Add polling proxy support for kubernetes-agent-tentacle container

source/Octopus.Tentacle.Client.Tests/ExecuteShellScriptCommandBuilderTests.cs, source/Octopus.Tentacle.Client/Scripts/Models/Builders/ExecuteScriptCommandBuilder.cs
For resilience we need to be able to specify the ScriptTicket so as to prevent scripts from re-running.
=> Allow callers too specify the script ticket

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesRawScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
A customer appears to be having resource contention with a large number of script pods. They would like to be able to modify the resource requirements of script pods.
Adds support for a new environment variable `OCTOPUS__K8STENTACLE__PODRESOURCEJSON` which contains the serialized resource requirements provided by the helm chart in https://github.com/OctopusDeploy/helm-charts/pull/225
We then deserialize this to a `V1ResourceRequirements` and use it
=> Support configuring script pod resource requirements

docker/readme.md
Octopus is a [GitHub secret scanning partner](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program), and this means we receive alerts when GitHub detects an Octopus API key in a public GitHub repository.
The `docker/README.md` file in this repository contains an example Octopus API key that is triggering an alert because it matches the same pattern as an actual Octopus API key. In this PR, I've replaced it with `API-xxx`.
After this PR is merged, GitHub will stop notifying us that an "exposed" API key is in this repository.
N/A
N/A
=> Remove Example Octopus API Key

docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/agent-values.yaml
There is currently a [bug](https://octopus.zendesk.com/agent/tickets/196514) in the `configure-and-run.sh` script of the Kubernetes Tentacle that causes the registration to fail if a space is included in the target tag string.
This is caused by the bash script incorrectly interpreting the space inside the tag string as a delimiter, and thereby passing an extra token to the tentacle executable.
Fixes the bug by [reverting back](https://github.com/OctopusDeploy/OctopusTentacle/pull/969/files#diff-6dfa40bcf0d67e7161ca980e8437fbda23940d37b92e1645ca31d1cecdbdc637L170) to having a single bash function that performs the tentacle registration. 
The reason that this single function approach works is because it builds a local ARGS array, adds elements to it (which may include strings with …
=> Fix bug to allow spaces in Kubernetes agent target tags

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
A customer would like to set affinity and tolerations on the script pods. This allows customers to set affinity & tolerations to force the script pods to only schedule on specific nodes.
This should allow customers who are running EKS with BottleRocket to avoid scheduling script pods on BottleRocket nodes
Shortcut story: [sc-86605]
=> Add support for custom script pod affinity & tolerations

docker/kubernetes-agent-tentacle/Dockerfile, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
Customers have asked if they are configure the Kubernetes agent pods to not run as the root user. K8s has this capability via the pod `securityContext` values (and `runAsUser`).
This PR exposes a new environment variable `OCTOPUS_K8STENTACLE_PODSECURITYCONTEXTJSON` that is provided by the Helm chart that is then deserialized and set on the script pod.
Shortcut story: [sc-87998]
=> Add ability to set script pod security contexts

.nuke/build.schema.json, build.ps1, build.sh, build/Build.Pack.cs, build/Build.Tests.cs, build/Build.cs, build/Signing.cs, build/_build.csproj, build/test-scripts/integration/common/dotnet-install.sh, build/test-scripts/integration/common/setup-vm-agent.sh, dotnet-install.ps1, global.json, source/Octopus.Tentacle.CommonTestUtils/OctopusPackageDownloader.cs, source/Octopus.Tentacle.CommonTestUtils/TestCertificates.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesAgentIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesAgentMetricsIntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesClusterOneTimeSetUp.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesScriptServiceV1IntegrationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesClusterInstaller.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/KubernetesScriptServiceV1DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/Proxies/MethodInvocationHookProxyDecorator.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/Proxies/MethodLoggingProxyDecorator.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/Proxies/MethodUsageProxyDecorator.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/Proxies/ServiceProxy.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/ScriptServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/ScriptServiceV2DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration.Common/Builders/Decorators/TentacleServiceDecoratorBuilderExtensions.cs, source/Octopus.Tentacle.Tests/Security/Certificates/CertificateEncoderFixture.cs, source/Tentacle.sln
To help support migrating to .NET 8 this change updates the SDK to use net8.0 when building and for the Nuke build project.
This does not change the target framework of Tentacle, which will continue to target the existing frameworks in this PR.
- Nuke Build updated from 6.0.3 -> 8.0.0
- OctoVersion updated from 0.2.1058 -> 0.3.400
- OctopusTools updated from 7.4.3289 -> 9.1.7
- Fixed/suppressed warnings for issues raised by new compiler tooling (primarily defining the actual nullability of variables)
=> Update build/sdk to net8.0

source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodService.cs, source/Octopus.Tentacle/Services/Scripts/Kubernetes/KubernetesScriptServiceV1.cs
Kubernetes script pod cancellation takes into account the grace seconds of the script pod. Which means that after cancellation, the pod can run for up to 30s before termination. This PR changes this logic to delete the pod with `0` grace seconds, it also returns a completed state from the `CancelScript` call so that the script observation stops calling `CancelScript` multiple times.
Script execution is now forced to not have a grace period. We also immediately mark the task as completed, which then stops the script observation loop from calling `CancelScript` again, which can result in an erroneous error as the pod has been removed.
This is also consistent with the normal shell scripts, which return complete & the canceled error code as soon as the cancellation token is marked as …
=> Change Kubernetes script cancellation to better handle pod deletion

docker/linux/Dockerfile, docker/linux/scripts/configure-tentacle.sh, docker/windows/Scripts/configure-tentacle.ps1
https://github.com/OctopusDeploy/OctopusTentacle/pull/46 added the `--proxy` CLI arg. This change adds the ability to pass the value for that token as an environment variable into the container.
- Shortcut: [SC-90394]
- Resolves #996
Specifying `ProxyName` as an environment variable to the container will add it as the value of the  `--proxy` CLI flag.
This has been running in production for approximately a year. We're trying to unwind our customizations on top of the upstream image.
=> Makes --proxy added in #46 available to Docker containers

build/Build.Pack.cs
As part of PR #997, Kubernetes Tentacle was updated to use Debian 12 as the default image. In that update, a Debian 11-based version was also built to address compatibility issues with sha1rsa on Windows Server 2012R2, as Debian 11 still uses OpenSSL v1, which works with sha1rsa on that older OS.
However, it was later discovered that while OpenSSL v1 is compatible, it only functions at a security level (SECLEVEL) of 1 or lower. The default SECLEVEL for the Debian base image is 2, meaning the Kubernetes Tentacle wouldn't work on Debian 11 (in this special case) unless the SECLEVEL is manually lowered. The reason for this is that the permitted list of signature hash algorithms at SECLEVEL 2 does not include sha1rsa. More details [here](https://docs.google.com/document/d/1jgApNQDZYYbNWLopsyK- …
=> Remove Debian 11 Build for Kubernetes Tentacle

README.md, k8s-agent-debug-cluster-config/k8s-agent-debug-cluster.yaml, k8s-agent-debug-cluster-config/launchSettings.template.json, k8s-agent-debug-cluster-config/local-persistent-volume.yaml, k8s-agent-debug-cluster-config/local-storage-class.yaml, setup-k8s-agent-for-local-debug.sh, source/Octopus.Tentacle/Diagnostics/OctopusLogsDirectoryRenderer.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPhysicalFileSystem.cs, source/Octopus.Tentacle/Kubernetes/LocalMachineKubernetesClientConfigProvider.cs, source/Octopus.Tentacle/Variables/EnvironmentVariables.cs
Previously we haven't had a nice way of debugging the Kubernetes Agent, and we never had a way to debug it locally. Looking forward we might have more people using the Agent so it's a good idea to formalise the process of how to setup a developers environment to allow for local debugging.
I've created a script, along with a few small changes to the Tentacle code base to help guide engineers through the process of setting up their environment to locally debug the agent.
Caveats: It has only been tested on MacOS - updates are probably required for Windows and Linux.
https://octopus.zoom.us/rec/share/Az-ugVGNR8Mg7_WWZa8FCwiqg4nJwgDkVx9N41EbzaHNPFn9EcygVZwG51sY_skE.Q913692PVXEdOXG3?startTime=1727326867000
Passcode: &429gPqU
=> Add script to guide developers through setting up their environment to allow locally debugging the Kubernetes Agent

source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/KubernetesClusterInstaller.cs
We are changing the default version string in Server to `v4.*.*` so we get the latest version in the `v4` major version range.
This just updates this to be the same.
Shortcut story: [sc-94493]
=> Change NFS CSI driver version to v4.*.*

source/Octopus.Tentacle.Tests.Integration/Support/ExceptionContractAssertionBuilder.cs
My build failed due to a flaky test:
https://build.octopushq.com/test/-3830879800243621547?currentProjectId=TeamFireAndMotion_OctopusTentacle_TentacleVLatest_net80&expandTestHistoryChartSection=true
It looks like there is stray whitespace in one of the expected exception messages that is causing the test to occasionally fail.
This PR removes the stray whitespace.
Was that whitespace deliberate?
Do we need to cater for messages both with and without the extra space?
=> Fix flaky test: Remove stray whitespace in expected exception messages.

build/Build.Pack.cs, source/Chocolatey/OctopusDeploy.Tentacle.SelfContained.nuspec, source/Chocolatey/chocolateyInstall.ps1
We are introducing the OctopusDeploy.Tentacle.SelfContained package for the public to be able to install the Octopus Self Contained Tentacle on Windows through Chocolatey.
Both should be published on Chocolatey through the internal Tentacle deployment process.
We will pack two nuspec files rather than one, resulting in two nuget packages being made available:
- OctopusDeploy.Tentacle
- OctopusDeploy.Tentacle.SelfContained
Tested on a branch build and seems to be working, and is downloadable publicly
=> Introduce OctopusDeploy.Tentacle.SelfContained Chocolatey package 

linux-packages/packaging-scripts/package.sh, linux-packages/packaging-scripts/unsigned/package.sh
[sc-95170]
Fixes https://github.com/OctopusDeploy/Issues/issues/9060
```
ben@bens-suse:/etc> sudo zypper install tentacle
Refreshing service 'Basesystem_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'Desktop_Applications_Module_x86_64'.
Refreshing service 'Development_Tools_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service 'Python_3_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Refreshing service 'Server_Applications_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: 1: nothing provides 'openssl-libs' needed by the to be installed tentacle-8.2.2297-1.x86_64
Solution 1: do not …
```
=> update rpm dependency

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
A customer needs support for making outbound connections via a HTTP/S proxy in script pods.
To support this, we need to set the `http_proxy`/`HTTP_PROXY`, `https_proxy`/`HTTPS_PROXY` and `no_proxy`/`NO_PROXY` environment variables in the pod. This is being set in a new secret being added in https://github.com/OctopusDeploy/helm-charts/pull/329
We use a secret as the proxy URI might have authentication credentials in it
This PR just sets the `envFrom` on the script pods to a `secretRef` with the name of the proxies secret created when set
Shortcut story: [sc-95481]
=> Add support for Kubernetes agent script pod proxies secret

source/Octopus.Tentacle.Tests.Integration/Support/TentacleTestCaseSourceAttribute.cs
The `Net60ClientNet48Service` test category is no longer used in build configurations and can be removed.
Instead, the newer `Net80ClientNet48Service` test category should be used instead.
Tests should run as before
- Quality :heavy_check_mark:
- TeamCity tests, especially integration tests on Windows that use this category
=> Remove Net60ClientNet48Service test category

docker/kubernetes-agent-tentacle/dev/Dockerfile
The debug container does not work due to these missing env vars
Adds them back in!
=> Fix missing env-vars in k8s debug dockerfile

docker/kubernetes-agent-tentacle/bootstrapRunner/bootstrapRunner.go, source/Octopus.Tentacle.Tests/Kubernetes/PodLogLineParserFixture.cs, source/Octopus.Tentacle/Kubernetes/Crypto/ScriptPodLogEncryptionKeyGenerator.cs, source/Octopus.Tentacle/Kubernetes/Crypto/ScriptPodLogEncryptionKeyProvider.cs, source/Octopus.Tentacle/Kubernetes/InMemoryTentacleScriptLog.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodLogService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/PodLogLineParser.cs
We identified an issue with #1047 where an automated upgrade would fail as the script pod would be created by an non-pod log encryption Tentacle, but then after the upgrade the pod log encryption Tentacle would fail as it expects all pod logs to be encrypted.
We have added a new `e` to the log lines generated by the bootstrap runner. This control character indicates the line is encrypted. An absence of this control char (or being set to `p`) indicates that the line is in plaintext and should not be decrypted
This PR also include minor nit changes from the review of #1047 
Shortcut story: [sc-98480]
=> Add a encryption control character to the log lines

dotnet-install.ps1
The [.NET install links recently changed](https://devblogs.microsoft.com/dotnet/critical-dotnet-install-links-are-changing/). We maintain a modified copy of the `dotnet-install.ps1` script in this repository to ensure TLS 1.2 is used when the script is run on older operating systems.
This change applies these changes to the current latest script.
Script updated to reflect the upstream changes. Note: the upstream version includes the new domains, but still has some references to the old domains (`dotnetcli.azureedge.net` and `dotnetbuilds.azureedge.net`). There is an upstream issue tracking this: https://github.com/dotnet/install-scripts/issues/559
=> Update dotnet-install.ps1 script for new CDN urls

docker/kubernetes-agent-tentacle/bootstrapRunner/bootstrapRunner.go
Part of https://github.com/OctopusDeploy/Issues/issues/9202
This PR addresses an issue where long text cannot be written to Octopus output variables when deploying via the Octopus Kubernetes Agent. The problem is caused by the default max buffer size of the `bufio.Scanner `in the bootstrap runner, which is limited to 64 KiB. This causes large outputs (e.g., from Terraform plans) to not be written to service message logs.
[sc-100196]
- The max buffer size for the Scanner has been increased to allow larger outputs, with the maximum size set to 10 MiB, which aligns with Kubernetes' default max container log size.
- Ensures the reader is closed after scanning (regardless of error) to properly close the pipe, allowing the command process to terminate without hanging while waiting for the pipe …
=> Increase the maximum buffer size of the Kubernetes agent bootstrapRunner's stream readers

source/Octopus.Tentacle.Client/Scripts/ObservingScriptOrchestrator.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionAdditionalScripts.cs
While testing out the new event driven tentacle client in Octopus Server, we found that E2E tests were failing because log output was coming through twice.
When the event driven tentacle client work was done, it maintained a quirk with script service V1. The quirk was that calling "Complete Script" could return output. This output had to be written to the Octopus Server task log, but only script service V1 was doing this.
During the refactor, we ended up maintaining the output logging after "Complete Script", but it was put in a common place which will get run for all service types, not just V1.
Where we call `OnScriptStatusResponseReceived` after we "Complete Script" is the correct location. However, if we do not receive any output (e.g. if we are the V2 or K8s script service), then we …
=> Fixing bug where script output would appear twice in task logs

source/Octopus.Tentacle.Client/ITentacleClient.cs, source/Octopus.Tentacle.Client/ScriptExecutor.cs, source/Octopus.Tentacle.Client/Scripts/IScriptExecutor.cs, source/Octopus.Tentacle.Client/Scripts/ObservingScriptOrchestrator.cs, source/Octopus.Tentacle.Client/ServiceHelpers/AllClients.cs, source/Octopus.Tentacle.Client/TentacleClient.cs
It was decided that exposing the `ScriptExecutor` was not ideal. Instead, we wanted to use the one publicly visible endpoint to be used. That would be the `TentacleClient`.
We have now exposed the operations that the `ScriptExecutor` can do onto the `TentacleClient`, and are calling them through the `TentacleClient` instead.
=> Putting ScriptExecutor functionality into TentacleClient

source/Octopus.Tentacle.Client/ScriptExecutor.cs, source/Octopus.Tentacle.Client/Scripts/KubernetesScriptServiceV1Executor.cs, source/Octopus.Tentacle.Client/Scripts/ObservingScriptOrchestrator.cs, source/Octopus.Tentacle.Client/Scripts/ScriptOperationExecutionResult.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV1Executor.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV2Executor.cs, source/Octopus.Tentacle.Contracts/ScriptStatus.cs
Exit code is always an integer in the response. It makes it easier to work with in Octopus Server as well. So let's just make it not nullable for now to make life easier in Octopus Server, and we can deal with the entire situation later.
Also, we had a parameter name that was incorrect. That is being fixed here as well.
=> Making ExitCode not nullable, plus renaming command context parameter

dotnet-install.ps1
The azureedge.net domain is no longer used to provide the .NET SDK. This PR synchronises our forked version of the dotnet-install.ps1 script with the upstream version.
- References to azureedge.net have been removed
- The `NoCdn` parameter of the script has been removed (as per upstream)
This PR primarily changes the old references to domains that are no longer used to serve the dotnet SDK. This keeps the changes relatively constrained following the most recent synchronisation:
- #1053
To compare with the current version upstream, the following command can be run (tested in bash):
```
diff --color=auto --strip-trailing-cr <(curl --location https://dot.net/v1/dotnet-install.ps1) dotnet-install.ps1
```
=> Re-sync dotnet-install.ps1 to remove azureedge.net

docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh, docker/kubernetes-agent-tentacle/scripts/register.sh, source/Octopus.Tentacle.Kubernetes.Tests.Integration/KubernetesAgent/KubernetesAgentMigrateFromPreinstallationTest.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/Tooling/HelmDownloader.cs, source/Octopus.Tentacle.Kubernetes.Tests.Integration/Setup/Tooling/ToolDownloader.cs, source/Octopus.Tentacle.Tests/Commands/MigratePreInstalledKubernetesDeploymentTargetCommandTest.cs, source/Octopus.Tentacle/Commands/MigratePreInstalledKubernetesDeploymentTargetCommand.cs, source/Octopus.Tentacle/Kubernetes/ConfigMapNames.cs, source/Octopus.Tentacle/Kubernetes/Configuration/ConfigMapKeyValueStore.cs, source/Octopus.Tentacle/Kubernetes/Crypto/KubernetesMachineEncryptionKeyProvider.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/UnimplementedKubernetesClientConfigProvider.cs, source/Octopus.Tentacle/Program.cs
As a part of the Kubernetes Monitor, we need to have the Kubernetes agent registered prior to the agent registering with server. To do this, we need to run a pre-installation script.
To keep this backwards-compatible, we can't touch any existing resources, or helm may delete files that have data in them.
As such, we have opted for the pre-installation hook to write the configuration to a different configmap and secret, and have created a new command in tentacle to migrate the configuration to the final destination.
* There's a new command in Tentacle which copies the data from the pre-installation configmap and secret and overwrites the destination data to use it
* This should only ever happen if the agent _was not registered_ in the existing configmap
* There's a new script that's been …
=> Allow the Kubernetes agent to be registered with a pre-install hook

source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/ShowOneTimeSetupLogInfo.cs, source/Octopus.Tentacle.Tests.Integration/TentacleIntegrationSetupCanBeLongRunningClickHereToSeeLogsFixtures.cs
Some devs are left wondering what on earth is happening the first time Integration tests run locally.
What happens is we download potentially GBs of data to download  tentacle for testing.
The Fixture which does that is renamed to hint it could be slow and how to view progress:
=> Rename the setup fixture to tell users it is slow to run and clicking it will show logs

source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/LinuxTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetchers/NugetTentacleFetcher.cs
- Fixing the tar command where the path contains spaces.
- Fixes downloading older tentacles. The issue was it was trying to use net8 versions of old version of tentacle which did not exist.
=> Fix running Integration Tests on OSX

docker/kubernetes-agent-tentacle/scripts/configure-and-run.sh
[sc-104721]
For a polling tentacle, the register machine command relies on the polling proxy config to work. In a locked down environment where access to the Octopus instance must go via a proxy, the proxy configuration must be setup prior to registering.
This PR changes the order so proxy configuration is in place prior to registration.
Fixes #1074 
=> changed proxy config order for k8s agent

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
A new version of Kubernetes, `1.32` was released late last year and the SDK supporting it was released in Jan.
Our support policy is that we will update the SDK within 3 months of the SDK being released.
Updates the Kubernetes SDK to `16.0.2` which supports `1.32`.
Updates BounchCastle crypto to `2.5.1` as this dependency was updated in the K8s SDK. Looking at the [changes](https://www.bouncycastle.org/download/bouncy-castle-c/?filter=c_sharp%3Drelease-2-5-0), there doesn't appear to be any reason for concern about this upgrade.
=> Upgrade to Kubernetes SDK to support 1.32

source/Octopus.Tentacle/Kubernetes/KubernetesRawScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
The Kubernetes Agent currently supports setting custom resource limits on main script pods, but not init script pods - they have a fixed value defined in the agent itself.
This PR sets the init script pod resource limits to the values specified for the main script pods.
I added two agents to my local cluster, one with the old version, one with this version. 
They both had a memory limit set: `--set agent.scriptPods.resources.limits.memory="273Mi"`  
Only this version actually applied that limit.
Left is before, right is after:
=> Link init script pod resource limits to main script pod limits

.github/workflows/approve-renovate-pull-request.yml, .github/workflows/update-dependencies.yml, renovate-config.js, source/Octopus.Manager.Tentacle.Tests/Octopus.Manager.Tentacle.Tests.csproj, source/Octopus.Tentacle.Client.Tests/Octopus.Tentacle.Client.Tests.csproj, source/Octopus.Tentacle.CommonTestUtils/Octopus.Tentacle.CommonTestUtils.csproj, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests/DependenciesTest.cs, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj
Prevent the FluentAssertions version from auto-updating as [v8 upwards is not FOSS](https://github.com/fluentassertions/fluentassertions/pull/2943).
[sc-102264]
Renovate will not generate PRs relating to FluentAssertion updates. 
=> Update FluentAssertions to v7 and lock

README.md, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
Adds support for annotations to ScriptPods.
Fixes [issues/1070](https://github.com/OctopusDeploy/OctopusTentacle/issues/1070)
```
[POD EVENT] FailedMount | MountVolume.SetUp failed for volume "octopus-agent-octopus-deploy-pvc" : rpc error: code = FailedPrecondition desc = failed to find the sidecar container in Pod spec (Count: 9)
The Kubernetes Pod 'octopus-script-slpfqrh5k2l2ju2gqfseg' is in the 'Pending' phase
```
Validate that my understanding of the configuration and JSON parsing pattern is correct as I am unsure about the inline JSON parsing into a `Dictionary<string, string>` pattern.
Setting `OCTOPUS__K8STENTACLE__PODANNOTATIONSJSON='{foo: "bar"}'` should be enough to validate that the JSON parsing is correct and validating that any created Script Pods …
=> Adds support for ScriptPods having configurable Annotations (#1070)

renovate-config.js, source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
We have a significant backlog of dependency update PRs accumulating in the Tentacle repository since Renovate was enabled last year. These PRs are currently rate-limited, and it is important for us to prevent the backlog from growing further. It's clear that we need to stay on top of dependency updates.
To address this issue, we are establishing [a structured dependency update process](https://whimsical.com/dependency-updates-process-AvRrJa2scNomVv7gq2Rz3N) for both the Tentacle and Halibut repositories. As part of this initiative, we will introduce a "Green-means-go" PR message, similar to the dependency update procedures used in Octopus Server. This will allow developers to approve certain dependencies with minimal scrutiny, while ensuring that other dependencies receive the appropriate …
=> Introduce "Green-means-go" Renovate PR Messages

source/Octopus.Tentacle.Tests.Integration/Util/RunningScriptFixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceFixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs, source/Octopus.Tentacle.Tests/Scripts/ScriptIsolationMutexFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesRawScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Program.cs, source/Octopus.Tentacle/Scripts/RunningScript.cs, source/Octopus.Tentacle/Scripts/ScriptIsolationMutex.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs, source/Octopus.Tentacle/Util/ScriptsModule.cs
This is a step in the direction of testing tentacle in process.
Script isolation was done using a static,
now it is done with a singleton.
We already have tests for this.
=> Isolation mutex is no longer a static

source/Octopus.Tentacle.CommonTestUtils/Builders/ScriptBuilder.cs, source/Octopus.Tentacle.Tests.Integration/ScriptsAreGivenRequiredEnvironmentVariables.cs, source/Octopus.Tentacle.Tests.Integration/Util/RunningScriptFixture.cs, source/Octopus.Tentacle.Tests.Integration/Util/SilentProcessRunnerFixture.cs, source/Octopus.Tentacle/Scripts/RunningScript.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs, source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs, source/Octopus.Tentacle/Util/SilentProcessRunner.cs
This is a step in the direction of testing tentacle in process
Since we will need to provide env vars per script service rather than CLR wide.
=> Allow the script services to supply env vars to scripts

source/Octopus.Tentacle.Tests/Scripts/ScriptStateStoreTests.cs, source/Octopus.Tentacle/Scripts/ScriptStateStore.cs
We should have a test that we can read previously written versions of the state store, and now we do.
fixes: https://github.com/OctopusDeploy/OctopusTentacle/issues/1095
=> Add script state store test, test reading old files

source/Octopus.Tentacle.CommonTestUtils/OctopusPackageDownloader.cs
Sometimes the win10 test are hung, looking at the dump we see:
```
[2] 00007ff8616a6588 (0) System.Net.Http.HttpConnection+<ReadAsync>d__87
[2] 00007ff8616a69c0 (0) System.Net.Http.HttpConnection+ContentLengthReadStream+<ReadAsync>d__3
[2] 00007ff861485800 (4) Octopus.Tentacle.CommonTestUtils.OctopusPackageDownloader+<AttemptToDownloadPackage>d__1
[2] 00007ff861485bc8 (0) Octopus.Tentacle.CommonTestUtils.OctopusPackageDownloader+<DownloadPackage>d__0
[2] 00007ff8614861d8 (1) Octopus.Tentacle.Tests.Integration.Support.TentacleFetchers.NugetTentacleFetcher+<DownloadAndExtractFromUrl>d__4
[2] 00007ff8614868d0 (0) Octopus.Tentacle.Tests.Integration.Support.TentacleFetchers.NugetTentacleFetcher+<GetTentacleVersion>d__3
[2] 00007ff861486698 (2) …
```
=> Timeout downloading tentacles

source/Octopus.Tentacle.Tests.Integration/ClientFileTransferRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetriedWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceNonV1IsNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionWillAttemptACancelCallWhenGetStatusFails.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/ListeningResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/PollingResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/TcpConnectionUtilities.cs
We already head something that sets up the connection to be killed at just the right time.
Lets use that instead of trying to see when the connection is setup from the port forwarder.
=> Use existing helper to kill the connection at the right time

source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
When the kubernetes agent runs as a worker, a secret for helm is mounted into the `/root/agent_upgrade/` folder. The `/root` folder has a default ownership of `700`, which means that when running as a non-root user (I.E. in OpenShift), the agent upgrade and health check would fail with `EACCESS` whenever attempting to run helm.
This fixes the bug by adding an additional mount in `/tmp`, a more reasonable place. A change to the upgrade script will need to be made to point to the new location (if it exists) as well.
=> Add extra mount for agent upgrade

source/Octopus.Tentacle.Client.Tests/ScriptServiceV1ExecutorTests.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV1Executor.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs
For ScriptServiceV1, a call to `GetStatus` may not return the full log
information if the logs have not yet been flushed. This change updates
the client to perform a second GetStatus check to attempt to fetch any
additional logs.
- Updates the script executor in the Tentacle client for ScriptServiceV1 to run an extra call to `GetStatus` when the process is complete
- Resolves #1117
- Quality
- Test Coverage
=> Run GetStatus check twice when complete on SSV1

source/Octopus.Tentacle/Kubernetes/KubernetesContainerExtensionMethods.cs, source/Octopus.Tentacle/Kubernetes/KubernetesCustomResourceService.cs, source/Octopus.Tentacle/Kubernetes/KubernetesModule.cs, source/Octopus.Tentacle/Kubernetes/KubernetesRawScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs, source/Octopus.Tentacle/Kubernetes/ScriptPodTemplateCustomResource.cs, telepresence-config/launchSettings.template.json
Allows the script pods and containers to have certain fields controlled via a new custom resource, the `scriptpodtemplate.agent.octopus.com`
When creating the script pod, we now try and read the old custom resource. If this exists, we then use its pod spec, script container and/or the watchdog container spec's to build the base specs/containers.
We then modify these with any additional changes we require for the pods to execute correctly
=> Use script pod template custom resource to create pods and containers

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
This PR updates the Halibut package from version 8.1.1503 to 8.1.1514 in the Octopus.Tentacle.Contracts project.
Adds a minor fix to Redis message stream wrappers, where the stream was not disposed before using the result of the stream. Does not affect tentacle.
=> Update Halibut to version 8.1.1514

source/Octopus.Tentacle.Client/Execution/RpcCallExecutor.cs, source/Octopus.Tentacle.Client/ScriptExecutor.cs, source/Octopus.Tentacle.Client/Scripts/KubernetesScriptServiceV1Executor.cs, source/Octopus.Tentacle.Client/Scripts/ObservingScriptOrchestrator.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV1Executor.cs, source/Octopus.Tentacle.Client/Scripts/ScriptServiceV2Executor.cs, source/Octopus.Tentacle.Client/TentacleClient.cs
[whimsical](https://whimsical.com/adding-tracing-to-tentacleclient-DghPwsZpzqU6rAsrBi4EXR)
We would like more visibility into what Octopus Server is doing when it communicates with tentacles.
Adds traces to TentacleClient
Previously this trace would have just shown the toplevel TentacleExecutionTarget.Execute, with no child spans to explain what Execute is actually doing. Now, we can see that it's doing two RPC calls, then polling on GetStatus until CompleteScript.
(Note: Ignore the "Octopus.Tests" tree node names, they only appear because I'm capturing these traces from an integration test because it's convenient. If this was running in the real server they'd say Octopus.Server)
We can expand the Rpc calls and discover that the slow Rpc call was ICapbilitiesServiceV2.GetCapabilities
The …
=> Adding OTEL Traces to TentacleClient
