source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Updating Halibut version to fix concurrency issue
=> Update nuget versions

source/Octopus.Tentacle/Octopus.Tentacle.csproj
10.4.1 includes a change which removes write-access for groups/all users to the service file.
Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/17
=> Update Shared to 10.4.1

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj
Nightly build is failing https://octopusdeploy.slack.com/archives/C03FX2F2ZFB/p1660119217547509
=> Remove duplicate PackageReference

docker/run-tests.ps1
Octopus.Client no longer runs on net452 https://github.com/OctopusDeploy/OctopusClients/pull/680
=> net462 instead of net452

build/Build.Pack.cs, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj, source/Solution Items/SolutionInfo.cs
=> Version Octopus.Tentacle.Contracts assembly

source/Octopus.Tentacle/Octopus.Tentacle.csproj
`SqlClient` is not used/needed by Tentacle.
`SqlClient`
No `SqlClient`
=> remove reference to sqlclient

source/Octopus.Manager.Tentacle/Octopus.Manager.Tentacle.csproj, source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle/Octopus.Tentacle.csproj
This brings in the fix from Halibut https://github.com/OctopusDeploy/Halibut/pull/198
Addresses https://github.com/OctopusDeploy/Issues/issues/7956
=> bump halibut

docker/windows/Scripts/healthcheck-tentacle.ps1
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/444
=> Correct health check config location

.github/CODEOWNERS
Team Server at Scale is assuming ownership of this repository.
=> Change code owner from FnM to SaS

source/Octopus.Tentacle.Contracts/ScriptExitCodes.cs, source/Octopus.Tentacle.Contracts/ScriptTicket.cs, source/Octopus.Tentacle.Tests.Integration/Util/RunningScriptFixture.cs, source/Octopus.Tentacle.Tests/Integration/ScriptServiceFixture.cs, source/Octopus.Tentacle/Scripts/BashScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/IScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/IScriptWorkspaceFactory.cs, source/Octopus.Tentacle/Scripts/RunningScript.cs, source/Octopus.Tentacle/Scripts/ScriptTicketFactory.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspace.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspaceFactory.cs, source/Octopus.Tentacle/Services/Scripts/ScriptService.cs
This PR refactors some logic out of ScriptService for reuse in future changes to add a ScriptServiceV2
🟢  Server: Upgrade Tentacle https://github.com/OctopusDeploy/OctopusDeploy/pull/17841
=> Refactor logic out of ScriptService for reuse

source/Octopus.Tentacle.Tests.Integration/PollingTentacleTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleClientBuilderExtensionMethods.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Makes the integration tests smaller making it easier to focus on what is being tested.
slightly smaller tests.
=> Reduce the code required for integration testing

source/Octopus.Tentacle.Contracts/Legacy/HalibutRuntimeExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ListeningTentacleTests.cs, source/Octopus.Tentacle.Tests.Integration/PollingTentacleTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleClientBuilderExtensionMethods.cs
Refactor the Polling and Listening Tentacle Builders to remove code duplication
=> Refactor Polling/Listening Tentacle Builders

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/PollingResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/PortForwarderDataSentLogger.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/BiDirectionalDataTransferObserver.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/DataTransferObserverBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/DataTransferObserverCombiner.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/IDataTransferObserver.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/PortForwarderBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/SocketPump.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/TcpPump.cs
Attempts to push some of the complex logic out of the tests themselves.
=> Push the killing of the TCP connection on receiving message out of the test.

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV2IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Server.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/CountingCallsScriptServiceDecorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/CountingCallsScriptServiceV2Decorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/ErrorRecordingScriptServiceV2Decorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/LogCallsToScriptServiceV2Decorator.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/ScriptServiceV2DecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/PollingResponseMessageTcpKiller.cs
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 
=> Cleanup ClientScriptExecutionCanRecoverFromNetworkIssues

source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionAdditionalScripts.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptArgumentsWork.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptFilesAreSent.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionWorksWithMultipleVersions.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs, source/Octopus.Tentacle.Tests.Integration/FileTransferServiceTests.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceTests.cs, source/Octopus.Tentacle.Tests.Integration/ScriptServiceV2IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/AllTentacleTypesWithV1V2ScriptServices.cs, source/Octopus.Tentacle.Tests.Integration/Support/CartesianProduct.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleTypesToTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/V1OnlyAndV2ScriptServiceTentacleVersions.cs, source/Octopus.Tentacle.Tests.Integration/Util/RunTestsInParallelLocallyIfEnabledButNeverOnTeamCityAttribute.cs
Updates lots of tests to also test listening tentacles.
Adds support for running tests in parallel locally.
Update the client and tentacle builder so that a port forwarder is not created by default.
=> Adds listening tests to many of the existing tests

source/Octopus.Tentacle.CommonTestUtils/Octopus.Tentacle.CommonTestUtils.csproj, source/Octopus.Tentacle.Tests.Integration/Octopus.Tentacle.Tests.Integration.csproj, source/Octopus.Tentacle.Tests.Integration/Support/DirectoryInfoExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Support/ListeningTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/PollingTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/RunningTentacle.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/CancellationTokenExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/PortForwarder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/SocketPump.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/TcpPump.cs, source/Octopus.Tentacle.Tests/Octopus.Tentacle.Tests.csproj, source/Tentacle.sln
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 
=> Net48 Hangs - Try and Fix it

source/Octopus.Tentacle.Client/Retries/CancellationTokenExtensionMethods.cs, source/Octopus.Tentacle.Client/Retries/CancellationTokenSourceExtensionMethods.cs, source/Octopus.Tentacle.Client/Retries/RpcCallRetryHandlerExtensionMethods.cs, source/Octopus.Tentacle.Client/Scripts/ScriptExecutionOrchestrator.cs, source/Octopus.Tentacle.Client/TentacleClient.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRpcRetryCancellationWork.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/Support/CancellationTokenExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/Support/IntegrationTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/RpcCallStage.cs, source/Octopus.Tentacle.Tests.Integration/Support/TemporaryDirectory.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/TentacleServiceDecoratorBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/ListeningResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/PollingResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpTentacleHelpers/ResponseMessageTcpKiller.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/PortForwarder.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/SocketPump.cs, source/Octopus.Tentacle.Tests.Integration/Util/TcpUtils/TcpPump.cs
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 
=> Cancellation Tests and Fix Cancellation

source/Octopus.Tentacle.CommonTestUtils/DataStreamExtensionMethods.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetried.cs
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 
=> Verify upload download is retried and is successful.

docker/windows/Dockerfile, docker/windows/Scripts/configure-and-run-tentacle-wrapper.ps1
[SC-48697](https://app.shortcut.com/octopusdeploy/story/48697/issue-with-windows-tentacle-container-running-in-fargate)
We have a reported issue where Windows Tentacle Container fails to run in ECS Fargate. The issue is linked back to the open [containerd issue](https://github.com/containerd/containerd/issues/5067) when parsing the _shell_ form for `ENTRYPOINT` syntax. The known workaround is to use the [_exec_ form](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact:~:text=has%20two%20forms%3A-,The%20exec%20form,-%2C%20which%20is%20the).
Fixes [issue-8143](https://github.com/OctopusDeploy/Issues/issues/8143)
The interaction between `ENTRYPOINT` and `CMD` is now changed due to the usage of _exec_ syntax, where additional `CMD` will now be appended …
=> Updated ENTRYPOINT to exec syntax for Windows Dockerfile to workaround containerd issue

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Bump the version so that we can get Halibut observability.
Related to https://github.com/OctopusDeploy/Issues/issues/8229
=> Bumping Halibut to use the new observability fixes

source/Octopus.Tentacle/AssemblyInfo.cs
I forgot to bump the Major version and need a PR to do it!! 
=> Small change to allow major version to be bumped

source/Octopus.Tentacle.Tests/Integration/ScriptServiceV2Fixture.cs
Allow more leeway for a time-based test that is flakey
=> Allow more leeway for a time based test that is flakey

source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientFileTransfersAreRetriedWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionAdditionalScripts.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionIsolationMutex.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptArgumentsWork.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptFilesAreSent.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceV1IsNotRetried.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionWorksWithMultipleVersions.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutorObservesScriptObserverBackoffStrategy.cs, source/Octopus.Tentacle.Tests.Integration/Support/AllCombinations.cs, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/ITentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/LinuxTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/NugetTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleBinaryCache.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleTypesAndCommonVersionsToTest.cs, source/Octopus.Tentacle.Tests.Integration/Support/TentacleVersions.cs, source/Octopus.Tentacle.Tests.Integration/Support/VersionDependentTentacleFetcher.cs, source/Octopus.Tentacle.Tests.Integration/Support/WindowsOnlyNugetBinsTentacleFetcher.cs
Test against Tentacle `7.0.1` which was the first version with ScriptServiceV2 added
=> Test against Tentacle 7.0.1 which was the first version with ScriptServiceV2 added

source/Octopus.Tentacle.Contracts/ClientServices/IAsyncClientCapabilitiesServiceV2.cs, source/Octopus.Tentacle.Contracts/ClientServices/IAsyncClientFileTransferService.cs, source/Octopus.Tentacle.Contracts/ClientServices/IAsyncClientScriptService.cs, source/Octopus.Tentacle.Contracts/ClientServices/IAsyncClientScriptServiceV2.cs
Add async client service interfaces
=> Add async client service interfaces

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj, source/Octopus.Tentacle.Tests.Integration/Support/ClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Support/Legacy/LegacyClientAndTentacleBuilder.cs, source/Octopus.Tentacle.Tests.Integration/Util/PendingRequestQueueHelpers/CancellationObservingPendingRequestQueueFactory.cs, source/Octopus.Tentacle/Communications/HalibutInitializer.cs
Update Halibut to 6.0.1136
Make Tentacle use the Halibut Client and Limits will be done at a later stage.
=> Update Halibut to 6.0.1136

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
=> Bump Halibut to 6.0.1307

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
=> Bumping Halibut

source/Octopus.Tentacle.Tests.Integration/ClientGathersRpcCallMetrics.cs, source/Octopus.Tentacle.Tests/Client/RpcCallRetryHandlerFixture.cs
=> Fix flakey tests

source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs
Attempt to fix what looks like a timing issue in ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled
Occasional flakey tests results e.g. https://build.octopushq.com/buildConfiguration/TeamFireAndMotion_OctopusTentacleNet48_SensibleDefaultsChainFullChain/9718957?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildProblemsSection=true
It may not be fixed but there are a series of green runs 
=> Attempt to fix what looks like a timing issue in ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled

source/Octopus.Tentacle/Services/Scripts/ScriptServiceV2.cs
[sc-60771]
It was noticed that `ScriptServiceV2` was not disposing the `CancellationTokenSource` that it was creating.
Related to OctopusDeploy/Issues#8229
Since we were not disposing the cancelation token source, this would build up over time.
When we remove the `RunningScriptWrapper`, we now also dispose it (along with the `CancellationTokenSource` it is wrapping).
To make this safer, we moved creation of the `CancellationTokenSource` into `RunningScriptWrapper` itself.
This does mean that we create a `CancellationTokenSource` earlier. But 99.9% of the time we will end up going through the same code path as before. Ignoring exceptions, the only time we don't go down that path is if the Tentacle has restarted, and we loaded the state from disk. In which case, it doesn't matter if we …
=> Disposing of the CancellationTokenSource used in script service V2

source/Octopus.Tentacle.Tests.Integration/TentacleCommandLineTests.cs
This PR fixes a poison merge causing `main` to not compile
=> Fix poison merge

source/Octopus.Tentacle.Tests.Integration/TentacleCommandLineTests.cs
Run more console tests in isolation to avoid possible tests interacting with each other and causing failures.
=> Run more console tests in isolation

source/Octopus.Tentacle.Contracts/ScriptServiceV3Alpha/KubernetesJobScriptExecutionContext.cs
So I can make changes in Server (as I need a new `Octopus.Tentacle.Contracts` nuget package), I'm pulling this file out of #690 .
Shortcut story: [sc-59580]
=> Add KubernetesJobScriptExecutionContext

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs
Just providing an entry point for configuring the job TTL to be smaller for testing
=> Allow configuration of Job TTL

source/Octopus.Tentacle.Client/Scripts/ScriptOrchestratorFactory.cs
Identified by @nathanwoctopusdeploy, this looks like it was accidentally removed in #637 
Could be a source of the test flakiness
=> Re-add some exception handling when determining script service to use

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Updating Halibut to the version that enables timeouts for web sockets
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/729
=> Updating Halibut to the version that enables timeouts for web sockets

source/Octopus.Tentacle.Tests/Integration/ScriptServiceV3AlphaFixture.cs, source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/Scripts/KubernetesJobOutputStreamWriter.cs, source/Octopus.Tentacle/Kubernetes/Scripts/KubernetesJobScriptExecutor.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs, source/Octopus.Tentacle/Scripts/ScriptWorkspace.cs, source/Octopus.Tentacle/Services/ServicesModule.cs, source/Octopus.Tentacle/Util/OctopusPhysicalFileSystem.cs
Just doing some cleanup and code re-arranging
- Changed default Job TTL to 1min as 30min was turning out to be quite excessive 😄 
- Set the os affinity for the nodes to be linux (we currently only support linux nodes)
- Move some code around
=> Move the Kubernetes scripts files under Kubernetes folder

source/Octopus.Tentacle.Tests.Integration/Support/ExceptionContractAssertionBuilder.cs
Add missing cancellation error message that can be thrown 
`Expected string "The operation was cancelled" to contain at least one of the strings: {"Script execution was cancelled", "A task was canceled."}.`
```
System.OperationCanceledException: The operation was cancelled
---> Halibut.HalibutClientException: An error occurred when sending a request to 'https://localhost:53884/', after the request began: The operation was canceled.
---> System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Halibut.Util.AsyncEx.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, CancellationToken cancellationToken)
at Halibut.Transport.TcpClientExtensions.ConnectWithTimeoutAsync(TcpClient client, String host, Int32 …
```
=> Add missing cancellation error message that can be thrown when establishing a connection in Halibut

source/Octopus.Tentacle.Tests.Integration/WorkspaceCleanerTests.cs
Fix flakey WhenCompleteScriptIsNotCalled_ThenWorkspaceShouldGetDeletedWhenScriptFinishesRunning test
Deleting a workspace is best effort (try three times and fail silently). If something is locking files or folders then the workspace may fail to be deleted but this is by design.
This makes testing the workspace cleaner reliably somewhat difficult as it is valid for a workspace to not be deleted.
This PR attempts to work around this for the test, trying to correctly identify a failure that is "valid" vs an issue and a real test failure.
=> Fix flakey WhenCompleteScriptIsNotCalled_ThenWorkspaceShouldGetDeletedWhenScriptFinishesRunning test

.github/pull_request_template.md
We renamed `master` to `main` in OctopusDeploy/Issues
Updates doc links accordingly
=> Update links to OctopusDeploy/Issues

source/Octopus.Tentacle/Configuration/Instances/ApplicationInstanceSelector.cs
Cleaning up after some changes I made for #project-k8s-agent
Just making this a little less verbose as it was unnecessary.
=> Small tidy-up of ApplicationInstanceSelector

source/Octopus.Tentacle/Configuration/ConfigurationModule.cs
Part of #project-k8s-agent
I made a boo boo and broke tentacle manager by not including some required type registrations. In https://github.com/OctopusDeploy/OctopusTentacle/pull/674
[Slack thread](https://octopusdeploy.slack.com/archives/C03SG0LFJHX/p1705997305750549)
=> Add required type registration for Tentacle Manager

source/Octopus.Manager.Tentacle/App.xaml.cs, source/Octopus.Manager.Tentacle/Proxy/ProxyWizardLauncher.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/ReviewAndRunScriptTabViewModel.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/TentacleSetupWizardLauncher.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/Views/ReviewAndRunScriptTabView.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/SetupWizard/Views/ReviewAndRunScriptTabView.xaml, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleManager/TentacleManagerView.xaml.cs, source/Octopus.Manager.Tentacle/TentacleConfiguration/TentacleModule.cs
We want to add some automated tests to Tentacle Manager as part of the [Tentacle Manager on .NET](https://app.shortcut.com/octopusdeploy/epic/68113/tentacle-manager-on-windows-net-core) project.
We first need to make the Tentacle Manager project testable by automated tests (e.g. NUnit) by separating the UI logic from the business logic. This will allow the automated tests to exercise most of the code (i.e. everything _not_ in a UI component) without the pain of dealing with UI threads and Dispatchers etc.
This PR refactors the InstallTab component in TentacleManager to separate its business logic from the view.
[sc-70325]
There should be *zero visible changes* from an end-user's perspective. The intent is that the functionality is completely unchanged, but the code base is in a better …
=> Refactor InstallTab.cs

source/Octopus.Tentacle/Kubernetes/KubernetesConfig.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesJob.cs
This is required so that we can get that info from health checks, so that we can support automatic updates.
=> Add Helm Environment Variables to kubernetes jobs 

source/Octopus.Tentacle.Tests.Integration/Support/SetupFixtures/TurnOnTraceLoggingForLogFileForLatestTentacle.cs, source/Octopus.Tentacle/Startup/OctopusProgram.cs, source/Octopus.Tentacle/Tentacle.exe.nlog
My previous attempt at add pod logs doesn't seem to work properly. I'm not sure how that slipped by but anyways, this seems to fix it.
=> Fix pod logs (and dynamically updating the log level in general)

source/Octopus.Tentacle/Communications/TentacleCommunicationsModule.cs
Fixes: https://github.com/OctopusDeploy/OctopusTentacle/issues/727
[SC-66372]
=> Use Recommended halibut timeouts and limits

docker/kubernetes-tentacle/scripts/configure-and-run.sh
Follow up a comment in #840, cleans up the logic in the launch script for the kubernetes tentacle
=> Cleanup Kubernetes Tentacle docker launch script

source/Octopus.Tentacle.Contracts/Services/Capabilities/IAsyncCapabilitiesServiceV2.cs
@samdanaei  This is the interface we needed in your test PR.
We should always have exposed this interface like this.
=> Expose IAsyncCapabilitiesServiceV2, maintaining location of service

source/Octopus.Tentacle.Tests.Integration/CapabilitiesServiceV2Test.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanBeCancelledWhenRetriesAreEnabled.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionCanRecoverFromNetworkIssues.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionRetriesTimeout.cs, source/Octopus.Tentacle.Tests.Integration/ClientScriptExecutionScriptServiceNonV1IsNotRetriedWhenRetriesAreDisabled.cs, source/Octopus.Tentacle.Tests.Integration/Util/Builders/Decorators/CapabilitiesServiceV2DecoratorBuilder.cs
We have decorator methods that better indicate the intent of the decorators. Using these decorators requires less juggling of generic type parameters and the need to pass the name of the decorated method.
- Minor changes made to `GetCapabilitiesClientDecorator` to support decorating a method with both before and after decorations.
- The `AfterGetCapabilities` decorator was updated to execute even if the decorated method raised an exception. The response will be `null` in this situation.
- Updates to tests to leverage these updated decorators
Shortcut: [SC-69397]
Example test code
```csharp
await using var clientAndTentacle = await tentacleConfigurationTestCase.CreateBuilder()
.WithTentacleServiceDecorator(new TentacleServiceDecoratorBuilder() …
```
=> Use friendlier service decorators for CapabilitiesService

source/Octopus.Tentacle.Tests/Kubernetes/KubernetesOrphanedPodCleanerTests.cs, source/Octopus.Tentacle.Tests/Kubernetes/KubernetesPodMonitorTests.cs, source/Octopus.Tentacle/Kubernetes/KubernetesOrphanedPodCleaner.cs, source/Octopus.Tentacle/Kubernetes/KubernetesPodMonitor.cs, source/Octopus.Tentacle/Kubernetes/Scripts/RunningKubernetesPod.cs
[sc-71685]
Just giving `PodStatus` and friends a more descriptive name.
=> Rename PodStatus to TrackedScriptPod

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Updates Halibut to 7.0.603 which includes the active tcp connection protections introduced in https://github.com/OctopusDeploy/Halibut/pull/599
No change in behaviour is expected as the new limit is not implemented
A server PR will be opened with the updated Tentacle packages to validated green builds before merging
=> Update Halibut to 7.0.603

source/Octopus.Tentacle/Kubernetes/KubernetesPodContainerRegistry.cs
Upgrade the default script pod image to use a slimmed down image that only has the required dependencies.
[sc-70343]
=> Update ScriptPod default image

source/Octopus.Tentacle/Octopus.Tentacle.csproj
We need to update Octopus Client in Tentacle because we've made updates to [Octopus Client](https://github.com/OctopusDeploy/OctopusClients/pull/830) and [Server](https://github.com/OctopusDeploy/OctopusDeploy/pull/22989) for Kubernetes Tentacle functionality.
[sc-67693]
It looks like all we need to do is update the Octopus Client version as there are no compile issues when upgrading.
=> Update Octopus Client for Tentacle

docker/kubernetes-tentacle/scripts/configure-and-run.sh
I just noticed this bash script was not formatted consistently so I just did a `Format Document` in Visual Studio Code.
=> Fix formatting for configure-and-run.sh

source/Octopus.Tentacle.Tests/Kubernetes/ReferenceCountingKeyedBinarySemaphoreTests.cs, source/Octopus.Tentacle/Kubernetes/Synchronisation/Internal/ReferenceCountingKeyedBinarySemaphore.cs
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/main/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 
=> Adjust test to focus on thread blocking rather than disposal

source/Octopus.Tentacle/Commands/RegisterMachineCommand.cs, source/Octopus.Tentacle/Octopus.Tentacle.csproj
Also fix Tenanted Deployment Participation parsing to be case insensitive
[sc-80799]
=> Update Machine registrations to allow Tenant slugs to be passed in

source/Octopus.Tentacle/Kubernetes/KubernetesScriptPodCreator.cs
These changes didn't get pushed before I merged #971  😢 
=> Order image pull secrets

linux-packages/packaging-scripts/package.sh, linux-packages/packaging-scripts/unsigned/package.sh
Previous change #1021 broke the installation for RHEL8 and AL2
Fixes https://github.com/OctopusDeploy/OctopusTentacle/issues/1023 
This will break SLES 15 until we can implement a better solution https://github.com/OctopusDeploy/OctopusTentacle/issues/1023#issuecomment-2416513319
=> rollback rpm package dependencies

build/Build.cs
I think we actually need to copy these around, like we do for everything else we publish.
=> Copy to local packages

source/Octopus.Tentacle.Contracts/Services/FileTransfer/IAsyncFileTransferService.cs, source/Octopus.Tentacle/Services/FileTransfer/FileTransferService.cs
This should have always been in contracts so that other systems can mock out tentacle.
=> Move file transfer service to contracts

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Which provides support for compressing messages in the redis queue and storing DataStreamMetadata as byte[].
None of the changes actually impact tentacle.
=> Update halibut to 8.1.1485

source/Octopus.Tentacle/Kubernetes/LocalMachineKubernetesClientConfigProvider.cs, telepresence-config/launchSettings.template.json, telepresence.sh
This is a small script to use telepresence to remote into a cluster and act as if tentacle is running from that cluster. This is great for troubleshooting permission issues and anything to do with service accounts.
=> Add telepresence script

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
This fixes a bug in the watcher and also makes it possible to have the in memory log actually log to in memory only.
- https://github.com/OctopusDeploy/Halibut/pull/675
- https://github.com/OctopusDeploy/Halibut/pull/674
The changes wont affect tentacle itself.
=> Upgrade Halibut to 8.1.1503

source/Octopus.Tentacle.Contracts/Octopus.Tentacle.Contracts.csproj
Adds:
- https://github.com/OctopusDeploy/Halibut/pull/688
- https://github.com/OctopusDeploy/Halibut/pull/686
- https://github.com/OctopusDeploy/Halibut/pull/685
- https://github.com/OctopusDeploy/Halibut/pull/684
- https://github.com/OctopusDeploy/Halibut/pull/683
- https://github.com/OctopusDeploy/Halibut/pull/677
None of these changes impact Tentacle, they are mostly non functional changes for the Redis PRQ. The last PR adds an opt in change which does not impact Tentacle.
=> Upgrade halibut to 8.1.1591
